/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.9.0.0; DO NOT EDIT. */

#nullable enable

namespace MediaClient.Media
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using MediaClient;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.9.0.0")]
    public partial class AudioEncoderConfiguration : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// Bitrate of the audio stream in kbps.
        /// </summary>
        [JsonPropertyName("Bitrate")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public int Bitrate { get; set; } = default!;

        /// <summary>
        /// Encoding of the audio stream.
        /// </summary>
        [JsonPropertyName("Encoding")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public AudioEncoding Encoding { get; set; } = default!;

        /// <summary>
        /// Defines the multicast settings that could be used for audio streaming
        /// </summary>
        [JsonPropertyName("Multicast")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public MulticastConfiguration Multicast { get; set; } = default!;

        /// <summary>
        /// User readable name of the audio encoder.
        /// </summary>
        [JsonPropertyName("Name")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public string Name { get; set; } = default!;

        /// <summary>
        /// Sample rate of the audio stream in kHz.
        /// </summary>
        [JsonPropertyName("SampleRate")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public int SampleRate { get; set; } = default!;

        /// <summary>
        /// The rtsp session timeout for the related audio stream
        /// </summary>
        [JsonPropertyName("SessionTimeout")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public TimeSpan SessionTimeout { get; set; } = default!;

        /// <summary>
        /// Unique identifier of the audio encoder.
        /// </summary>
        [JsonPropertyName("token")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public string Token { get; set; } = default!;

        /// <summary>
        /// Number of internal references currently using this configuration. This informational parameter is read-only. Deprecated for Media2 Service.
        /// </summary>
        [JsonPropertyName("UseCount")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public int UseCount { get; set; } = default!;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (Multicast is null)
            {
                throw new ArgumentNullException("Multicast field cannot be null");
            }
            if (Name is null)
            {
                throw new ArgumentNullException("Name field cannot be null");
            }
            if (Token is null)
            {
                throw new ArgumentNullException("token field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (Multicast is null)
            {
                throw new ArgumentNullException("Multicast field cannot be null");
            }
            if (Name is null)
            {
                throw new ArgumentNullException("Name field cannot be null");
            }
            if (Token is null)
            {
                throw new ArgumentNullException("token field cannot be null");
            }
        }
    }
}
