/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace MediaClient.Media
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using MediaClient;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class Exposure : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// The fixed exposure time used by the image sensor (μs).
        /// </summary>
        [JsonPropertyName("ExposureTime")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public float ExposureTime { get; set; } = default!;

        /// <summary>
        /// The fixed gain used by the image sensor (dB).
        /// </summary>
        [JsonPropertyName("Gain")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public float Gain { get; set; } = default!;

        /// <summary>
        /// The fixed attenuation of input light affected by the iris (dB). 0dB maps to a fully opened iris.
        /// </summary>
        [JsonPropertyName("Iris")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public float Iris { get; set; } = default!;

        /// <summary>
        /// Maximum value of exposure time range allowed to be used by the algorithm.
        /// </summary>
        [JsonPropertyName("MaxExposureTime")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public float MaxExposureTime { get; set; } = default!;

        /// <summary>
        /// Maximum value of the sensor gain range that is allowed to be used by the algorithm.
        /// </summary>
        [JsonPropertyName("MaxGain")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public float MaxGain { get; set; } = default!;

        /// <summary>
        /// Maximum value of the iris range allowed to be used by the algorithm.
        /// </summary>
        [JsonPropertyName("MaxIris")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public float MaxIris { get; set; } = default!;

        /// <summary>
        /// Minimum value of exposure time range allowed to be used by the algorithm.
        /// </summary>
        [JsonPropertyName("MinExposureTime")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public float MinExposureTime { get; set; } = default!;

        /// <summary>
        /// Minimum value of the sensor gain range that is allowed to be used by the algorithm.
        /// </summary>
        [JsonPropertyName("MinGain")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public float MinGain { get; set; } = default!;

        /// <summary>
        /// Minimum value of the iris range allowed to be used by the algorithm.
        /// </summary>
        [JsonPropertyName("MinIris")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public float MinIris { get; set; } = default!;

        /// <summary>
        /// Exposure ModeAuto – Enabled the exposure algorithm on the NVT.Manual – Disabled exposure algorithm on the NVT.
        /// </summary>
        [JsonPropertyName("Mode")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public ExposureMode Mode { get; set; } = default!;

        /// <summary>
        /// The exposure priority mode (low noise/framerate).
        /// </summary>
        [JsonPropertyName("Priority")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public ExposurePriority Priority { get; set; } = default!;

        /// <summary>
        /// Rectangular exposure mask.
        /// </summary>
        [JsonPropertyName("Window")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public Rectangle Window { get; set; } = default!;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (Window is null)
            {
                throw new ArgumentNullException("Window field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (Window is null)
            {
                throw new ArgumentNullException("Window field cannot be null");
            }
        }
    }
}
