/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.9.0.0; DO NOT EDIT. */

#nullable enable

namespace MediaClient.Media
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using MediaClient;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.9.0.0")]
    public partial class FocusConfiguration20
    {
        /// <summary>
        /// Mode of auto focus.
        /// </summary>
        [JsonPropertyName("AutoFocusMode")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public AutoFocusMode AutoFocusMode { get; set; } = default!;

        /// <summary>
        /// Default speed of focus adjustment.
        /// </summary>
        [JsonPropertyName("DefaultSpeed")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public float? DefaultSpeed { get; set; } = default;

        /// <summary>
        /// Parameter to set autofocus far limit (unit: meter).
        /// </summary>
        [JsonPropertyName("FarLimit")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public float? FarLimit { get; set; } = default;

        /// <summary>
        /// Parameter to set autofocus near limit (unit: meter).
        /// </summary>
        [JsonPropertyName("NearLimit")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public float? NearLimit { get; set; } = default;

    }
}
