/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace MediaClient.Media
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using MediaClient;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class GetAudioSourceConfigurationOptionsCommandResponse : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// This message contains the audio source configuration options. If a audio source configuration is specified, the options shall concern that particular configuration. If a media profile is specified, the options shall be compatible with that media profile. If no tokens are specified, the options shall be considered generic for the device.
        /// </summary>
        [JsonPropertyName("Options")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public AudioSourceConfigurationOptions Options { get; set; } = default!;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (Options is null)
            {
                throw new ArgumentNullException("Options field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (Options is null)
            {
                throw new ArgumentNullException("Options field cannot be null");
            }
        }
    }
}
