/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace MediaClient.Media
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using MediaClient;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class GetAudioEncoderConfigurationsCommandResponse : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// This element contains a list of audio encoder configurations.
        /// </summary>
        [JsonPropertyName("Configurations")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public List<AudioEncoderConfiguration> Configurations { get; set; } = default!;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (Configurations is null)
            {
                throw new ArgumentNullException("Configurations field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (Configurations is null)
            {
                throw new ArgumentNullException("Configurations field cannot be null");
            }
        }
    }
}
