/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace MediaClient.Media
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using MediaClient;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class GetGuaranteedNumberOfVideoEncoderInstancesRequestPayload : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// The Command request argument.
        /// </summary>
        [JsonPropertyName("GetGuaranteedNumberOfVideoEncoderInstances")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public GetGuaranteedNumberOfVideoEncoderInstances GetGuaranteedNumberOfVideoEncoderInstances { get; set; } = default!;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (GetGuaranteedNumberOfVideoEncoderInstances is null)
            {
                throw new ArgumentNullException("GetGuaranteedNumberOfVideoEncoderInstances field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (GetGuaranteedNumberOfVideoEncoderInstances is null)
            {
                throw new ArgumentNullException("GetGuaranteedNumberOfVideoEncoderInstances field cannot be null");
            }
        }
    }
}
