/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.9.0.0; DO NOT EDIT. */

#nullable enable

namespace MediaClient.Media
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using MediaClient;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.9.0.0")]
    public partial class GetMetadataConfigurationOptionsCommandResponse : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// Returns the metadata configuration options. 
        /// </summary>
        [JsonPropertyName("Options")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public MetadataConfigurationOptions Options { get; set; } = default!;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (Options is null)
            {
                throw new ArgumentNullException("Options field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (Options is null)
            {
                throw new ArgumentNullException("Options field cannot be null");
            }
        }
    }
}
