/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace MediaClient.Media
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using MediaClient;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class GetVideoEncoderConfigurationRequestPayload : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// The Command request argument.
        /// </summary>
        [JsonPropertyName("GetVideoEncoderConfiguration")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public GetVideoEncoderConfiguration GetVideoEncoderConfiguration { get; set; } = default!;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (GetVideoEncoderConfiguration is null)
            {
                throw new ArgumentNullException("GetVideoEncoderConfiguration field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (GetVideoEncoderConfiguration is null)
            {
                throw new ArgumentNullException("GetVideoEncoderConfiguration field cannot be null");
            }
        }
    }
}
