/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace MediaClient.Media
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using MediaClient;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class ImagingSettingsExtension203
    {
        /// <summary>
        /// Optional element to configure Image Defogging.
        /// </summary>
        [JsonPropertyName("Defogging")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public Defogging? Defogging { get; set; } = default;

        /// <summary>
        /// The 'Extension' Field.
        /// </summary>
        [JsonPropertyName("Extension")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public ImagingSettingsExtension204? Extension { get; set; } = default;

        /// <summary>
        /// Optional element to configure Image Noise Reduction.
        /// </summary>
        [JsonPropertyName("NoiseReduction")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public NoiseReduction? NoiseReduction { get; set; } = default;

        /// <summary>
        /// Optional element to configure Image Contrast Compensation.
        /// </summary>
        [JsonPropertyName("ToneCompensation")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public ToneCompensation? ToneCompensation { get; set; } = default;

    }
}
