/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace MediaClient.Media
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using MediaClient;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class Ipaddress
    {
        /// <summary>
        /// Indicates if the address is an IPv4 or IPv6 address.
        /// </summary>
        [JsonPropertyName("IpAddressType")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public Iptype IpAddressType { get; set; } = default!;

        /// <summary>
        /// IPv4 address.
        /// </summary>
        [JsonPropertyName("IPv4Address")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string? Ipv4address { get; set; } = default;

        /// <summary>
        /// IPv6 address
        /// </summary>
        [JsonPropertyName("IPv6Address")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string? Ipv6address { get; set; } = default;

    }
}
