/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace MediaClient.Media
{
    using System.Runtime.Serialization;
    using System.Text.Json.Serialization;

    [JsonConverter(typeof(JsonStringEnumMemberConverter))]
    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public enum Iptype
    {
        [EnumMember(Value = @"IPv4")]
        Ipv4 = 0,
        [EnumMember(Value = @"IPv6")]
        Ipv6 = 1,
        [EnumMember(Value = @"Unknown")]
        Unknown = 2,
    }
}
