/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace MediaClient.Media
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using MediaClient;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class JpegOptions : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// Supported encoding interval range. The encoding interval corresponds to the number of frames devided by the encoded frames. An encoding interval value of '1' means that all frames are encoded.
        /// </summary>
        [JsonPropertyName("EncodingIntervalRange")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public IntRange EncodingIntervalRange { get; set; } = default!;

        /// <summary>
        /// Supported frame rate in fps (frames per second).
        /// </summary>
        [JsonPropertyName("FrameRateRange")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public IntRange FrameRateRange { get; set; } = default!;

        /// <summary>
        /// List of supported image sizes.
        /// </summary>
        [JsonPropertyName("ResolutionsAvailable")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public List<VideoResolution> ResolutionsAvailable { get; set; } = default!;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (EncodingIntervalRange is null)
            {
                throw new ArgumentNullException("EncodingIntervalRange field cannot be null");
            }
            if (FrameRateRange is null)
            {
                throw new ArgumentNullException("FrameRateRange field cannot be null");
            }
            if (ResolutionsAvailable is null)
            {
                throw new ArgumentNullException("ResolutionsAvailable field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (EncodingIntervalRange is null)
            {
                throw new ArgumentNullException("EncodingIntervalRange field cannot be null");
            }
            if (FrameRateRange is null)
            {
                throw new ArgumentNullException("FrameRateRange field cannot be null");
            }
            if (ResolutionsAvailable is null)
            {
                throw new ArgumentNullException("ResolutionsAvailable field cannot be null");
            }
        }
    }
}
