/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.9.0.0; DO NOT EDIT. */

#nullable enable

namespace MediaClient.Media
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using MediaClient;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.9.0.0")]
    public partial class MetadataConfiguration : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// Defines whether the streamed metadata will include metadata from the analytics engines (video, cell motion, audio etc.)
        /// </summary>
        [JsonPropertyName("Analytics")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public bool? Analytics { get; set; } = default;

        /// <summary>
        /// The 'AnalyticsEngineConfiguration' Field.
        /// </summary>
        [JsonPropertyName("AnalyticsEngineConfiguration")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public AnalyticsEngineConfiguration? AnalyticsEngineConfiguration { get; set; } = default;

        /// <summary>
        /// Optional parameter to configure compression type of Metadata payload. Use values from enumeration MetadataCompressionType
        /// </summary>
        [JsonPropertyName("CompressionType")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string? CompressionType { get; set; } = default;

        /// <summary>
        /// Optional element to configure the streaming of events.
        /// </summary>
        [JsonPropertyName("Events")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public EventSubscription? Events { get; set; } = default;

        /// <summary>
        /// Optional parameter to configure if the metadata stream shall contain the Geo Location coordinates of each target.
        /// </summary>
        [JsonPropertyName("GeoLocation")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public bool? GeoLocation { get; set; } = default;

        /// <summary>
        /// Defines the multicast settings that could be used for video streaming
        /// </summary>
        [JsonPropertyName("Multicast")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public MulticastConfiguration Multicast { get; set; } = default!;

        /// <summary>
        /// User readable name of the metadata configuration.
        /// </summary>
        [JsonPropertyName("Name")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public string Name { get; set; } = default!;

        /// <summary>
        /// optional element to configure which PTZ related data is to include in the metadata stream
        /// </summary>
        [JsonPropertyName("PTZStatus")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public Ptzfilter? Ptzstatus { get; set; } = default;

        /// <summary>
        /// The rtsp session timeout for the related metadata stream.
        /// </summary>
        [JsonPropertyName("SessionTimeout")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public TimeSpan SessionTimeout { get; set; } = default!;

        /// <summary>
        /// Optional parameter to configure if the generated metadata stream should contain shape information as polygon
        /// </summary>
        [JsonPropertyName("ShapePolygon")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public bool? ShapePolygon { get; set; } = default;

        /// <summary>
        /// Unique identifier of the metadata configuration.
        /// </summary>
        [JsonPropertyName("token")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public string Token { get; set; } = default!;

        /// <summary>
        /// Number of internal references currently using this configuration. This informational parameter is read-only. Deprecated for Media2 Service.
        /// </summary>
        [JsonPropertyName("UseCount")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public int UseCount { get; set; } = default!;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (Multicast is null)
            {
                throw new ArgumentNullException("Multicast field cannot be null");
            }
            if (Name is null)
            {
                throw new ArgumentNullException("Name field cannot be null");
            }
            if (Token is null)
            {
                throw new ArgumentNullException("token field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (Multicast is null)
            {
                throw new ArgumentNullException("Multicast field cannot be null");
            }
            if (Name is null)
            {
                throw new ArgumentNullException("Name field cannot be null");
            }
            if (Token is null)
            {
                throw new ArgumentNullException("token field cannot be null");
            }
        }
    }
}
