/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.9.0.0; DO NOT EDIT. */

#nullable enable

namespace MediaClient.Media
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using MediaClient;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.9.0.0")]
    public partial class Mpeg4configuration
    {
        /// <summary>
        /// Determines the interval in which the I-Frames will be coded.
        /// </summary>
        [JsonPropertyName("GovLength")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public int GovLength { get; set; } = default!;

        /// <summary>
        /// the Mpeg4 profile, either simple profile (SP) or advanced simple profile (ASP)
        /// </summary>
        [JsonPropertyName("Mpeg4Profile")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public Mpeg4profile Mpeg4profile { get; set; } = default!;

    }
}
