/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace MediaClient.Media
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using MediaClient;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class RotateOptions : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// List of supported degree value for rotation.
        /// </summary>
        [JsonPropertyName("DegreeList")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public IntItems? DegreeList { get; set; } = default;

        /// <summary>
        /// The 'Extension' Field.
        /// </summary>
        [JsonPropertyName("Extension")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public RotateOptionsExtension? Extension { get; set; } = default;

        /// <summary>
        /// Supported options of Rotate mode parameter.
        /// </summary>
        [JsonPropertyName("Mode")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public List<RotateMode> Mode { get; set; } = default!;

        /// <summary>
        /// Signals if a device requires a reboot after changing the rotation.If a device can handle rotation changes without rebooting this value shall be set to false.
        /// </summary>
        [JsonPropertyName("Reboot")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public bool? Reboot { get; set; } = default;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (Mode is null)
            {
                throw new ArgumentNullException("Mode field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (Mode is null)
            {
                throw new ArgumentNullException("Mode field cannot be null");
            }
        }
    }
}
