/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace MediaClient.Media
{
    using System;
    using System.Collections.Generic;
    using Azure.Iot.Operations.Protocol;
    using Azure.Iot.Operations.Protocol.RPC;
    using Azure.Iot.Operations.Protocol.Models;
    using MediaClient;

    public static partial class Media
    {
        /// <summary>
        /// Specializes the <c>CommandInvoker</c> class for Command 'SetMetadataConfiguration'.
        /// </summary>
        public class SetMetadataConfigurationCommandInvoker : CommandInvoker<SetMetadataConfigurationRequestPayload, SetMetadataConfigurationResponseSchema>
        {
            /// <summary>
            /// Initializes a new instance of the <see cref="SetMetadataConfigurationCommandInvoker"/> class.
            /// </summary>
            public SetMetadataConfigurationCommandInvoker(ApplicationContext applicationContext, IMqttPubSubClient mqttClient)
                : base(applicationContext, mqttClient, "SetMetadataConfiguration", new Utf8JsonSerializer())
            {
                this.ResponseTopicPrefix = "clients/{invokerClientId}"; // default value, can be overwritten by user code

                TopicTokenMap["modelId"] = "dtmi:onvif:media;1";
                if (mqttClient.ClientId != null)
                {
                    TopicTokenMap["invokerClientId"] = mqttClient.ClientId;
                }
                TopicTokenMap["commandName"] = "SetMetadataConfiguration";
            }
        }
    }
}
