/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.9.0.0; DO NOT EDIT. */

#nullable enable

namespace MediaClient.Media
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using MediaClient;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.9.0.0")]
    public partial class VideoSourceConfigurationOptionsExtension
    {
        /// <summary>
        /// Optional extension for video source configuration options.
        /// </summary>
        [JsonPropertyName("Extension")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public VideoSourceConfigurationOptionsExtension2? Extension { get; set; } = default;

        /// <summary>
        /// Options of parameters for Rotation feature.
        /// </summary>
        [JsonPropertyName("Rotate")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public RotateOptions? Rotate { get; set; } = default;

    }
}
