/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.9.0.0; DO NOT EDIT. */

#nullable enable

namespace MediaClient.Media
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using MediaClient;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.9.0.0")]
    public partial class VideoSourceConfigurationExtension2
    {
        /// <summary>
        /// Optional element describing the geometric lens distortion. Multiple instances for future variable lens support.
        /// </summary>
        [JsonPropertyName("LensDescription")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public List<LensDescription>? LensDescription { get; set; } = default;

        /// <summary>
        /// Optional element describing the scene orientation in the camera’s field of view.
        /// </summary>
        [JsonPropertyName("SceneOrientation")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public SceneOrientation? SceneOrientation { get; set; } = default;

    }
}
