/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace MediaClient.Media
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using MediaClient;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class VideoSourceConfigurationOptionsExtension2 : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// Scene orientation modes supported by the device for this configuration.
        /// </summary>
        [JsonPropertyName("SceneOrientationMode")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public List<SceneOrientationMode> SceneOrientationMode { get; set; } = default!;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (SceneOrientationMode is null)
            {
                throw new ArgumentNullException("SceneOrientationMode field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (SceneOrientationMode is null)
            {
                throw new ArgumentNullException("SceneOrientationMode field cannot be null");
            }
        }
    }
}
