/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.9.0.0; DO NOT EDIT. */

#nullable enable

namespace MediaClient.Media
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using MediaClient;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.9.0.0")]
    public partial class VideoResolution
    {
        /// <summary>
        /// Number of the lines of the Video image.
        /// </summary>
        [JsonPropertyName("Height")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public int Height { get; set; } = default!;

        /// <summary>
        /// Number of the columns of the Video image.
        /// </summary>
        [JsonPropertyName("Width")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public int Width { get; set; } = default!;

    }
}
