/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace MediaClient.Media
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using MediaClient;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class VideoEncoderOptionsExtension
    {
        /// <summary>
        /// The 'Extension' Field.
        /// </summary>
        [JsonPropertyName("Extension")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public VideoEncoderOptionsExtension2? Extension { get; set; } = default;

        /// <summary>
        /// Optional H.264 encoder settings ranges.
        /// </summary>
        [JsonPropertyName("H264")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public H264options2? H264 { get; set; } = default;

        /// <summary>
        /// Optional JPEG encoder settings ranges.
        /// </summary>
        [JsonPropertyName("JPEG")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public JpegOptions2? Jpeg { get; set; } = default;

        /// <summary>
        /// Optional MPEG-4 encoder settings ranges.
        /// </summary>
        [JsonPropertyName("MPEG4")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public Mpeg4options2? Mpeg4 { get; set; } = default;

    }
}
