/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace MediaClient.Media
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using MediaClient;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class WhiteBalance20
    {
        /// <summary>
        /// Bgain (unitless).
        /// </summary>
        [JsonPropertyName("CbGain")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public float? CbGain { get; set; } = default;

        /// <summary>
        /// Rgain (unitless).
        /// </summary>
        [JsonPropertyName("CrGain")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public float? CrGain { get; set; } = default;

        /// <summary>
        /// The 'Extension' Field.
        /// </summary>
        [JsonPropertyName("Extension")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public WhiteBalance20extension? Extension { get; set; } = default;

        /// <summary>
        /// 'AUTO' or 'MANUAL'
        /// </summary>
        [JsonPropertyName("Mode")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public WhiteBalanceMode Mode { get; set; } = default!;

    }
}
