apiVersion: v1
kind: Secret
metadata:
  name: console-app-secret
type: Opaque
data:
  httpusername: some_base64_enc_username_for_http_service # Base64 encoded username
  httppassword: some_base64_enc_pwd_for_http_service  # Base64 encoded password
  sqlpassword: some_base64_enc_pwd_for_sql_server  # Base64 encoded sqlpassword. Same as the "SA_PASSWORD" if the default user "SA" is used.