---
# Source: contextualization-app/templates/secret.yaml
# templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: context-app-secret
type: Opaque
data:
  sqlpassword: "TXlFeHRyZW1lbHlTdHJvbmdwYXNzd29yZEAxMjM="
---
# Source: contextualization-app/templates/configmap.yaml
# templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: context-app-config
data:
  ENDPOINT_TYPE: "sql"
  AUTH_TYPE: "sqlbasic"
  REQUEST_INTERVAL_SECONDS: "10"
  DSS_KEY: "quality"
  MQTT_HOST: "aio-mq-dmqtt-frontend.default.svc.cluster.local"
  MQTT_CLIENT_ID: "app-id"
  SQL_SERVER_NAME: "sqlserver-service"
  SQL_DB_NAME: "MySampleDB"
  SQL_TABLE_NAME: "CountryMeasurements"
  USE_TLS: "true"
---
# Source: contextualization-app/templates/deployment.yaml
# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: context-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: context-app-deployment
  template:
    metadata:
      labels:
        app: context-app-deployment
    spec:
      containers:
      - name: context-app-deployment
        image: "dockeroliva/context-app-for-dss:x4"
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: context-app-config
        env:
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: context-app-secret
              key: sqlpassword
        - name: CA_FILE_PATH
          value: "/app/certs/cafile.crt"
        - name: CLIENT_CERT_FILE
          value: /etc/mqtt-certs/x509.crt
        - name: CLIENT_KEY_FILE
          value: /etc/mqtt-certs/x509.key
        volumeMounts:
        - name: ca-cert-file
          mountPath: /app/certs
          readOnly: true
        - name: client-certs
          mountPath: /etc/mqtt-certs
          readOnly: true
      volumes:
      - name: ca-cert-file
        secret:
          secretName: test-ca
          items:
          - key: tls.crt
            path: cafile.crt
      - name: client-certs
        secret:
          secretName: x509-secret
          items:
          - key: x509.crt
            path: x509.crt
          - key: x509.key
            path: x509.key
