replicaCount: 1

image:
  repository: dockeroliva/context-app-for-dss
  tag: x4
  pullPolicy: Always

endpointType: "sql"  # "http" or "sql"
authType: "sqlbasic"  # "httpbasic" or "sqlbasic"
useTLS: true
clientAuthMethod: "x509"  # "sat" or "x509"

volumes: 
  caCert: 
    secretName: test-ca

sat:
  tokenPath: "/app/secrets/sat_token"
  secretName: sat-token-secret

x509:
  certPath: "/etc/mqtt-certs/x509.crt"
  keyPath: "/etc/mqtt-certs/x509.key"
  secretName: x509-secret
  passwordEnabled: false

config:
  requestIntervalSeconds: "10"
  dssKey: "quality"
  mqttHost: "aio-mq-dmqtt-frontend.default.svc.cluster.local"
  mqttClientId: "app-id"
  httpBaseUrl: "http://my-backend-api-s.default.svc.cluster.local:80"
  httpPath: "contexts/quality"
  sqlServerName: "sqlserver-service"
  sqlDbName: "MySampleDB"
  sqlTableName: "CountryMeasurements"

secrets:
  httpUsername: "randomusername"
  httpPassword: "someVeryRandomPassword"
  sqlPassword: "MyExtremelyStrongpassword@123" 