apiVersion: v1
kind: Service
metadata:
  name: coredns-external
  namespace: kube-system
spec:
  sessionAffinity: None
  type: LoadBalancer
  ports:
  - name: dns
    nodePort: 30327
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    nodePort: 30327
    port: 53
    protocol: TCP
    targetPort: 53
  selector:
    k8s-app: kube-dns
