{
 "title": "Contoso data",
 "time": { "from": "2023-10-19T04:08:27.168Z", "to": "2023-10-19T04:15:49.616Z" },
 "templating": {
  "list": [
   { "name": "AssetID", "label": "Asset", "query": { "query": "edge_data\n| project AssetID" } }
  ]
 },
 "panels": [
  { "title": "Asset View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Anomalies (selected asset)",
   "type": "timeseries",
   "description": "Will give an error if more than \"All\" or no asset is selected.",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 1 },
   "targets": [
    {
     "database": "bakery_ops",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "edge_data\r\n| where AssetID == $AssetID\r\n| extend sourcetimestamp = todatetime(Timestamp)\r\n| where $__timeFilter(sourcetimestamp)\r\n| summarize VibrationAnomolyMetric = avg(VibrationAnomalyFactor) by bin(sourcetimestamp, 10s)\r\n| project sourcetimestamp, VibrationAnomolyMetric\r\n\r\n",
     "querySource": "raw"
    },
    {
     "database": "bakery_ops",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "edge_data\r\n| where AssetID == $AssetID\r\n| extend sourcetimestamp = todatetime(Timestamp)\r\n| where $__timeFilter(sourcetimestamp)\r\n| summarize TemperatureAnomalyMetric = avg(TemperatureAnomalyFactor) by bin(sourcetimestamp, 10s)\r\n| project sourcetimestamp, TemperatureAnomalyMetric",
     "querySource": "raw"
    },
    {
     "database": "bakery_ops",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "edge_data\r\n| where AssetID == $AssetID\r\n| extend sourcetimestamp = todatetime(Timestamp)\r\n| where $__timeFilter(sourcetimestamp)\r\n| summarize HumidityAnomalyMetric = avg(HumidityAnomalyFactor) by bin(sourcetimestamp, 10s)\r\n| project sourcetimestamp, HumidityAnomalyMetric",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Asset with most Vibration Anomalies ",
   "type": "stat",
   "description": "Asset that should be the target of Predictive Maintenace crew.",
   "gridPos": { "h": 7, "w": 3, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "bakery_ops",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "edge_data\r\n| extend sourcetimestamp = todatetime(Timestamp)\r\n| where $__timeFilter(sourcetimestamp)\r\n| summarize TotalCount = count(), AnomalyCount = countif(VibrationAnomaly == true) by AssetID\r\n| extend AnomalyPercentage = todouble(AnomalyCount) / todouble(TotalCount) * 100\r\n| top 1 by AnomalyPercentage desc\r\n| project AssetID",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Total Anomalies (per select asset) ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "bakery_ops",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "edge_data\r\n| where AssetID == $AssetID\r\n| extend sourcetimestamp = todatetime(Timestamp)\r\n| where $__timeFilter(sourcetimestamp)\r\n| where HumidityAnomaly == true or TemperatureAnomaly == true or VibrationAnomaly == true\r\n| summarize CountOfAnomalies = count()",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Total Anomalies (per select asset) ",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 17, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "bakery_ops",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "edge_data\r\n| where AssetID == $AssetID\r\n| extend sourcetimestamp = todatetime(Timestamp)\r\n| where $__timeFilter(sourcetimestamp)\r\n| summarize Anomalies = countif(HumidityAnomaly == true or TemperatureAnomaly == true or VibrationAnomaly == true),\r\n            NoAnomalies = countif(HumidityAnomaly == false and TemperatureAnomaly == false and VibrationAnomaly == false)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Process Variables (selected asset)",
   "type": "timeseries",
   "description": "Will give an error if more than 1 asset is selected.",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 10 },
   "targets": [
    {
     "database": "bakery_ops",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "edge_data\r\n| where AssetID == $AssetID\r\n| extend sourcetimestamp = todatetime(Timestamp)\r\n| where $__timeFilter(sourcetimestamp)\r\n| project sourcetimestamp, Vibration\r\n| summarize avg(Vibration) by bin(sourcetimestamp, 10s)\r\n",
     "querySource": "raw"
    },
    {
     "database": "bakery_ops",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "edge_data\r\n| where AssetID == $AssetID\r\n| extend sourcetimestamp = todatetime(Timestamp)\r\n| where $__timeFilter(sourcetimestamp)\r\n| project sourcetimestamp, Temperature\r\n| summarize avg(Temperature) by bin(sourcetimestamp, 10s)",
     "querySource": "raw"
    },
    {
     "database": "bakery_ops",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "edge_data\r\n| where AssetID == $AssetID\r\n| extend sourcetimestamp = todatetime(Timestamp)\r\n| where $__timeFilter(sourcetimestamp)\r\n| project sourcetimestamp, Humidity\r\n| summarize avg(Humidity) by bin(sourcetimestamp, 10s)",
     "querySource": "raw"
    }
   ]
  },
  { "title": "Vibration Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Redmond Slicer Vibration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "database": "bakery_ops",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "edge_data\r\n| where AssetID == \"Red_S1\"\r\n| extend sourcetimestamp = todatetime(Timestamp)\r\n| where $__timeFilter(sourcetimestamp)\r\n| project sourcetimestamp, Vibration\r\n| summarize avg(Vibration) by bin(sourcetimestamp, 10s)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Redmond Mixer Vibration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "database": "bakery_ops",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "edge_data\r\n| where AssetID == \"Tac_S1\"\r\n| extend sourcetimestamp = todatetime(Timestamp)\r\n| where $__timeFilter(sourcetimestamp)\r\n| project sourcetimestamp, Vibration\r\n| summarize avg(Vibration) by bin(sourcetimestamp, 10s)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Redmond Slicer Vibration Anomolies",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "bakery_ops",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "edge_data\r\n| where AssetID == \"Red_S1\"\r\n| extend sourcetimestamp = todatetime(Timestamp)\r\n| where $__timeFilter(sourcetimestamp)\r\n| summarize AvgVibrationAnomalyFactor = avg(VibrationAnomalyFactor) by bin(sourcetimestamp, 10s)\r\n| project sourcetimestamp, AvgVibrationAnomalyFactor",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Redmond Mixer Vibration Anomalies",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "bakery_ops",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "edge_data\r\n| where AssetID == \"Red_M1\"\r\n| extend sourcetimestamp = todatetime(Timestamp)\r\n| where $__timeFilter(sourcetimestamp)\r\n| summarize AvgVibrationAnomalyFactor = avg(VibrationAnomalyFactor) by bin(sourcetimestamp, 10s)\r\n| project sourcetimestamp, AvgVibrationAnomalyFactor",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Seattle Slicer Vibration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "database": "bakery_ops",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "edge_data\r\n| where AssetID == \"Sea_S1\"\r\n| extend sourcetimestamp = todatetime(Timestamp)\r\n| where $__timeFilter(sourcetimestamp)\r\n| project sourcetimestamp, Vibration\r\n| summarize avg(Vibration) by bin(sourcetimestamp, 10s)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Seattle Mixer Vibration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "database": "bakery_ops",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "edge_data\r\n| where AssetID == \"Sea_M1\"\r\n| extend sourcetimestamp = todatetime(Timestamp)\r\n| where $__timeFilter(sourcetimestamp)\r\n| project sourcetimestamp, Vibration\r\n| summarize avg(Vibration) by bin(sourcetimestamp, 10s)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Seattle Slicer Vibration Anomolies",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "bakery_ops",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "edge_data\r\n| where AssetID == \"Sea_S1\"\r\n| extend sourcetimestamp = todatetime(Timestamp)\r\n| where $__timeFilter(sourcetimestamp)\r\n| summarize AvgVibrationAnomalyFactor = avg(VibrationAnomalyFactor) by bin(sourcetimestamp, 10s)\r\n| project sourcetimestamp, AvgVibrationAnomalyFactor",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Seattle Mixer Vibration Anomalies",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "bakery_ops",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "edge_data\r\n| where AssetID == \"Sea_M1\"\r\n| extend sourcetimestamp = todatetime(Timestamp)\r\n| where $__timeFilter(sourcetimestamp)\r\n| summarize AvgVibrationAnomalyFactor = avg(VibrationAnomalyFactor) by bin(sourcetimestamp, 10s)\r\n| project sourcetimestamp, AvgVibrationAnomalyFactor",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Tacoma Slicer Vibration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "database": "bakery_ops",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "edge_data\r\n| where AssetID == \"Tac_S1\"\r\n| extend sourcetimestamp = todatetime(Timestamp)\r\n| where $__timeFilter(sourcetimestamp)\r\n| project sourcetimestamp, Vibration\r\n| summarize avg(Vibration) by bin(sourcetimestamp, 10s)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Tacoma Mixer Vibration ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "database": "bakery_ops",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "edge_data\r\n| where AssetID == \"Tac_M1\"\r\n| extend sourcetimestamp = todatetime(Timestamp)\r\n| where $__timeFilter(sourcetimestamp)\r\n| project sourcetimestamp, Vibration\r\n| summarize avg(Vibration) by bin(sourcetimestamp, 10s)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Tacoma Slicer Vibration Anomalies",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "bakery_ops",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "edge_data\r\n| where AssetID == \"Tac_S1\"\r\n| extend sourcetimestamp = todatetime(Timestamp)\r\n| where $__timeFilter(sourcetimestamp)\r\n| summarize AvgVibrationAnomalyFactor = avg(VibrationAnomalyFactor) by bin(sourcetimestamp, 10s)\r\n| project sourcetimestamp, AvgVibrationAnomalyFactor",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Tacoma Mixer Vibration Anomalies",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "database": "bakery_ops",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "edge_data\r\n| where AssetID == \"Tac_M1\"\r\n| extend sourcetimestamp = todatetime(Timestamp)\r\n| where $__timeFilter(sourcetimestamp)\r\n| summarize AvgVibrationAnomalyFactor = avg(VibrationAnomalyFactor) by bin(sourcetimestamp, 10s)\r\n| project sourcetimestamp, AvgVibrationAnomalyFactor",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Oven Process Parameters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "repeat": "AssetID",
   "collapsed": true,
   "panels": [
    {
     "title": "Sea_Oven Humidity",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "database": "bakery_ops",
       "expression": {
        "from": { "property": { "name": "raw_data", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "edge_data\n| where AssetID in (\"Sea_O1\")\n| top 1 by Timestamp desc\n| project Humidity",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Sea_Oven Temperature",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "bakery_ops",
       "expression": {
        "from": { "property": { "name": "raw_data", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "edge_data\n| where AssetID in (\"Sea_O1\")\n| top 1 by Timestamp desc\n| project Temperature",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Tac_Oven Humidity",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "database": "bakery_ops",
       "expression": {
        "from": { "property": { "name": "raw_data", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "edge_data\n| where AssetID in (\"Tac_O1\")\n| top 1 by Timestamp desc\n| project Humidity",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Tac_Oven Temperature",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "bakery_ops",
       "expression": {
        "from": { "property": { "name": "raw_data", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "edge_data\n| where AssetID in (\"Tac_O1\")\n| top 1 by Timestamp desc\n| project Temperature",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Red_Oven Humidity",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "database": "bakery_ops",
       "expression": {
        "from": { "property": { "name": "raw_data", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "edge_data\n| where AssetID in (\"Red_O1\")\n| top 1 by Timestamp desc\n| project Humidity",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Red_Oven Temperature",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "bakery_ops",
       "expression": {
        "from": { "property": { "name": "raw_data", "type": "string" }, "type": "property" },
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "edge_data\n| where AssetID in (\"Red_O1\")\n| top 1 by Timestamp desc\n| project Temperature",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Seattle Oven process parameters",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "database": "bakery_ops",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "edge_data\r\n| where AssetID == \"Sea_O1\"\r\n| extend sourcetimestamp = todatetime(Timestamp)\r\n| where $__timeFilter(sourcetimestamp)\r\n| project sourcetimestamp, Humidity, Temperature, AssetID\r\n| summarize AvgHumidity = avg(Humidity), AvgTemperature = avg(Temperature) by bin(sourcetimestamp, 10s)",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Tacoma Oven process parameters",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
     "targets": [
      {
       "database": "bakery_ops",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "edge_data\r\n| where AssetID == \"Tac_O1\"\r\n| extend sourcetimestamp = todatetime(Timestamp)\r\n| where $__timeFilter(sourcetimestamp)\r\n| project sourcetimestamp, Humidity, Temperature, AssetID\r\n| summarize AvgHumidity = avg(Humidity), AvgTemperature = avg(Temperature) by bin(sourcetimestamp, 10s)",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Redmond Oven process parameters",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
     "targets": [
      {
       "database": "bakery_ops",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "edge_data\r\n| where AssetID == \"Red_O1\"\r\n| extend sourcetimestamp = todatetime(Timestamp)\r\n| where $__timeFilter(sourcetimestamp)\r\n| project sourcetimestamp, Humidity, Temperature, AssetID\r\n| summarize AvgHumidity = avg(Humidity), AvgTemperature = avg(Temperature) by bin(sourcetimestamp, 10s)",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Seattle Oven Process Anomalies",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "database": "bakery_ops",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "edge_data\r\n| where AssetID == \"Sea_O1\"\r\n| extend sourcetimestamp = todatetime(Timestamp)\r\n| where $__timeFilter(sourcetimestamp)\r\n| summarize avg(HumidityAnomalyFactor), avg(TemperatureAnomalyFactor) by bin(sourcetimestamp, 10s)",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Tacoma Oven Process Anomalies",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "database": "bakery_ops",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "edge_data\r\n| where AssetID == \"Tac_O1\"\r\n| extend sourcetimestamp = todatetime(Timestamp)\r\n| where $__timeFilter(sourcetimestamp)\r\n| summarize avg(HumidityAnomalyFactor), avg(TemperatureAnomalyFactor) by bin(sourcetimestamp, 10s)",
       "querySource": "raw"
      }
     ]
    },
    {
     "title": "Seattle Oven Process Anomalies",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "database": "bakery_ops",
       "expression": {
        "groupBy": {
         "expressions": [],
         "type": "and"
        },
        "reduce": {
         "expressions": [],
         "type": "and"
        },
        "where": {
         "expressions": [],
         "type": "and"
        }
       },
       "query": "edge_data\r\n| where AssetID == \"Red_O1\"\r\n| extend sourcetimestamp = todatetime(Timestamp)\r\n| where $__timeFilter(sourcetimestamp)\r\n| summarize avg(HumidityAnomalyFactor), avg(TemperatureAnomalyFactor) by bin(sourcetimestamp, 10s)",
       "querySource": "raw"
      }
     ]
    }
   ]
  }
 ]
}