apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: server-cert
  namespace: azure-iot-operations
spec:
  secretName: custom-auth-server-cert
  commonName: "TestServer"
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - auth-server-template # Replace with your actual pod DNS name
  issuerRef:
    name: azure-iot-operations-aio-certificate-issuer
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: client-cert
  namespace: azure-iot-operations
spec:
  secretName: custom-auth-client-cert
  commonName: "TestClientCert"
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: azure-iot-operations-aio-certificate-issuer
    kind: ClusterIssuer
---
apiVersion: v1
kind: Pod
metadata:
  name: auth-server-template
  labels:
    app.kubernetes.io/name: AuthServerTemplate
spec:
  containers:
  # Main container for the auth server
  - name: auth-server-template
    image: ghcr.io/azure-samples/explore-iot-operations/auth-server-template:0.5.0
    imagePullPolicy: Always
    ports:
      - name: https
        containerPort: 443
    volumeMounts:
      - name: custom-auth-server-cert
        mountPath: /tls
    env:
    - name: SERVER_CERT_CHAIN
      value: /tls/tls.crt
    - name: SERVER_CERT_KEY
      value: /tls/tls.key
  volumes:
  - name: custom-auth-server-cert
    secret:
      secretName: custom-auth-server-cert
---
apiVersion: v1
kind: Service
metadata:
  name: auth-server-template
spec:
  selector:
    app.kubernetes.io/name: AuthServerTemplate
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
