/* Code generated by Azure.Iot.Operations.ProtocolCompiler; DO NOT EDIT. */

#nullable enable

namespace PTZ.dtmi_onvif_ptz__1
{
    public enum Enum_Onvif_Ptz_MoveStatus__1
    {
        UNKNOWN = 0,
        IDLE = 1,
        MOVING = 2,
    }
}
