/* Code generated by Azure.Iot.Operations.ProtocolCompiler; DO NOT EDIT. */

#nullable enable

namespace PTZ.dtmi_onvif_ptz__1
{
    public enum Enum_Onvif_Ptz_EFlipMode__1
    {
        Unknown = 0,
        OFF = 1,
        ON = 2,
        Extended = 3,
    }
}
