/* Code generated by Azure.Iot.Operations.ProtocolCompiler; DO NOT EDIT. */

#nullable enable

namespace PTZ.dtmi_onvif_ptz__1
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using PTZ;

    public class Object_Onvif_Ptz_PTZSpeed__1
    {
        /// <summary>
        /// Pan and tilt speed. The x component corresponds to pan and the y component to tilt. If omitted in a request, the current (if any) PanTilt movement should not be affected.
        /// </summary>
        [JsonPropertyName("PanTilt")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public Object_Onvif_Ptz_Vector2D__1? PanTilt { get; set; } = default;

        /// <summary>
        /// A zoom speed. If omitted in a request, the current (if any) Zoom movement should not be affected.
        /// </summary>
        [JsonPropertyName("Zoom")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public Object_Onvif_Ptz_Vector1D__1? Zoom { get; set; } = default;

    }
}
