/* Code generated by Azure.Iot.Operations.ProtocolCompiler; DO NOT EDIT. */

#nullable enable

namespace PTZ.dtmi_onvif_ptz__1
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using PTZ;

    public class Object_Onvif_Ptz_PTZSpaces__1
    {
        /// <summary>
        /// The Generic Pan/Tilt Position space is provided by every PTZ node that supports absolute Pan/Tilt, since it does not relate to a specific physical range. Instead, the range should be defined as the full range of the PTZ unit normalized to the range -1 to 1 resulting in the following space description.
        /// </summary>
        [JsonPropertyName("AbsolutePanTiltPositionSpace")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public List<Object_Onvif_Ptz_Space2DDescription__1>? AbsolutePanTiltPositionSpace { get; set; } = default;

        /// <summary>
        /// The Generic Zoom Position Space is provided by every PTZ node that supports absolute Zoom, since it does not relate to a specific physical range. Instead, the range should be defined as the full range of the Zoom normalized to the range 0 (wide) to 1 (tele). There is no assumption about how the generic zoom range is mapped to magnification, FOV or other physical zoom dimension.
        /// </summary>
        [JsonPropertyName("AbsoluteZoomPositionSpace")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public List<Object_Onvif_Ptz_Space1DDescription__1>? AbsoluteZoomPositionSpace { get; set; } = default;

        /// <summary>
        /// The generic zoom velocity space specifies a zoom factor velocity without knowing the underlying physical model. The range should be normalized from -1 to 1, where a positive velocity would map to TELE direction. A generic zoom velocity space description resembles the following.
        /// </summary>
        [JsonPropertyName("ContinuousPanTiltVelocitySpace")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public List<Object_Onvif_Ptz_Space2DDescription__1>? ContinuousPanTiltVelocitySpace { get; set; } = default;

        /// <summary>
        /// The generic Pan/Tilt velocity space shall be provided by every PTZ node, since it does not relate to a specific physical range. Instead, the range should be defined as a range of the PTZ unit’s speed normalized to the range -1 to 1, where a positive velocity would map to clockwise rotation or movement in the right/up direction. A signed speed can be independently specified for the pan and tilt component resulting in the following space description.
        /// </summary>
        [JsonPropertyName("ContinuousZoomVelocitySpace")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public List<Object_Onvif_Ptz_Space1DDescription__1>? ContinuousZoomVelocitySpace { get; set; } = default;

        /// <summary>
        /// The speed space specifies the speed for a Pan/Tilt movement when moving to an absolute position or to a relative translation. In contrast to the velocity spaces, speed spaces do not contain any directional information. The speed of a combined Pan/Tilt movement is represented by a single non-negative scalar value.
        /// </summary>
        [JsonPropertyName("PanTiltSpeedSpace")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public List<Object_Onvif_Ptz_Space1DDescription__1>? PanTiltSpeedSpace { get; set; } = default;

        /// <summary>
        /// The Generic Pan/Tilt translation space is provided by every PTZ node that supports relative Pan/Tilt, since it does not relate to a specific physical range. Instead, the range should be defined as the full positive and negative translation range of the PTZ unit normalized to the range -1 to 1, where positive translation would mean clockwise rotation or movement in right/up direction resulting in the following space description.
        /// </summary>
        [JsonPropertyName("RelativePanTiltTranslationSpace")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public List<Object_Onvif_Ptz_Space2DDescription__1>? RelativePanTiltTranslationSpace { get; set; } = default;

        /// <summary>
        /// The Generic Zoom Translation Space is provided by every PTZ node that supports relative Zoom, since it does not relate to a specific physical range. Instead, the corresponding absolute range should be defined as the full positive and negative translation range of the Zoom normalized to the range -1 to1, where a positive translation maps to a movement in TELE direction. The translation is signed to indicate direction (negative is to wide, positive is to tele).
        /// </summary>
        [JsonPropertyName("RelativeZoomTranslationSpace")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public List<Object_Onvif_Ptz_Space1DDescription__1>? RelativeZoomTranslationSpace { get; set; } = default;

        /// <summary>
        /// The speed space specifies the speed for a Zoom movement when moving to an absolute position or to a relative translation. In contrast to the velocity spaces, speed spaces do not contain any directional information.
        /// </summary>
        [JsonPropertyName("ZoomSpeedSpace")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public List<Object_Onvif_Ptz_Space1DDescription__1>? ZoomSpeedSpace { get; set; } = default;

    }
}
