/* Code generated by Azure.Iot.Operations.ProtocolCompiler; DO NOT EDIT. */

#nullable enable

namespace PTZ.dtmi_onvif_ptz__1
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using PTZ;

    public class Object_Onvif_Ptz_AbsoluteMove__1
    {
        /// <summary>
        /// A Position vector specifying the absolute target position.
        /// </summary>
        [JsonPropertyName("Position")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public Object_Onvif_Ptz_PTZVector__1? Position { get; set; } = default;

        /// <summary>
        /// A reference to the MediaProfile.
        /// </summary>
        [JsonPropertyName("ProfileToken")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string? ProfileToken { get; set; } = default;

        /// <summary>
        /// An optional Speed.
        /// </summary>
        [JsonPropertyName("Speed")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public Object_Onvif_Ptz_PTZSpeed__1? Speed { get; set; } = default;

    }
}
