/* Code generated by Azure.Iot.Operations.ProtocolCompiler; DO NOT EDIT. */

#nullable enable

namespace PTZ.dtmi_onvif_ptz__1
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using PTZ;

    public class Object_Onvif_Ptz_SendAuxiliaryCommandResponse__1
    {
        /// <summary>
        /// The response contains the auxiliary response.
        /// </summary>
        [JsonPropertyName("AuxiliaryResponse")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string? AuxiliaryResponse { get; set; } = default;

    }
}
