/* Code generated by Azure.Iot.Operations.ProtocolCompiler; DO NOT EDIT. */

#nullable enable

namespace PTZ.dtmi_onvif_ptz__1
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using PTZ;

    public class Object_Onvif_Ptz_Stop__1
    {
        /// <summary>
        /// Set true when we want to stop ongoing pan and tilt movements.If PanTilt arguments are not present, this command stops these movements.
        /// </summary>
        [JsonPropertyName("PanTilt")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public bool? PanTilt { get; set; } = default;

        /// <summary>
        /// A reference to the MediaProfile that indicate what should be stopped.
        /// </summary>
        [JsonPropertyName("ProfileToken")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public string? ProfileToken { get; set; } = default;

        /// <summary>
        /// Set true when we want to stop ongoing zoom movement.If Zoom arguments are not present, this command stops ongoing zoom movement.
        /// </summary>
        [JsonPropertyName("Zoom")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public bool? Zoom { get; set; } = default;

    }
}
