/* Code generated by Azure.Iot.Operations.ProtocolCompiler; DO NOT EDIT. */

#nullable enable

namespace PTZ.dtmi_onvif_ptz__1
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using PTZ;

    public class Object_PTZConfiguration_PanTiltLimits
    {
        /// <summary>
        /// A range of pan tilt limits.
        /// </summary>
        [JsonPropertyName("Range")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public Object_Onvif_Ptz_Space2DDescription__1? Range { get; set; } = default;

    }
}
