/* Code generated by Azure.Iot.Operations.ProtocolCompiler; DO NOT EDIT. */

#nullable enable

namespace PTZ.dtmi_onvif_ptz__1
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using PTZ;

    public class SetPresetRequestPayload : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// The Command request argument.
        /// </summary>
        [JsonPropertyName("SetPreset")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public Object_Onvif_Ptz_SetPreset__1 SetPreset { get; set; } = default!;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (SetPreset is null)
            {
                throw new ArgumentNullException("SetPreset field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (SetPreset is null)
            {
                throw new ArgumentNullException("SetPreset field cannot be null");
            }
        }
    }
}
