---
kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: default
  name: pg-pv
  labels:
    app: postgres
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: default
  name: pg-pvc
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: pg-config
  labels:
    app: postgres
data:
  POSTGRES_DB: database
  POSTGRES_USER: username
  POSTGRES_PASSWORD: password
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: pg-svc
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: postgres
  type: NodePort 
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: default
  name: pg-statefulset
  labels:
    app: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: mcr.microsoft.com/cbl-mariner/base/postgres:14
        envFrom:
        - configMapRef:
            name: pg-config
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pv-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pv-data
        persistentVolumeClaim:
          claimName: pg-pvc
