---
# Source: contextualization-app/templates/secret.yaml
# templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: context-app-secret
type: Opaque
data:
  httpusername: "aHA="
  httppassword: "YWxvaG9tb3Jh"
---
# Source: contextualization-app/templates/configmap.yaml
# templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: context-app-config
data:
  ENDPOINT_TYPE: "http"
  AUTH_TYPE: "httpbasic"
  REQUEST_INTERVAL_SECONDS: "10"
  DSS_KEY: "quality"
  MQTT_HOST: "aio-mq-dmqtt-frontend.default.svc.cluster.local"
  MQTT_CLIENT_ID: "app-id"
  HTTP_BASE_URL: "http://my-backend-api-s.default.svc.cluster.local:80"
  HTTP_PATH: "contexts/quality"
  USE_TLS: "true"
---
# Source: contextualization-app/templates/deployment.yaml
# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: context-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: context-app-deployment
  template:
    metadata:
      labels:
        app: context-app-deployment
    spec:
      containers:
      - name: context-app-deployment
        image: "dockeroliva/context-app-for-dss:x4"
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: context-app-config
        env:
        - name: HTTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: context-app-secret
              key: httpusername
        - name: HTTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: context-app-secret
              key: httppassword
        - name: CA_FILE_PATH
          value: "/app/certs/cafile.crt"
        - name: SAT_TOKEN_PATH
          value: /app/secrets/sat_token
        volumeMounts:
        - name: ca-cert-file
          mountPath: /app/certs
          readOnly: true
        - name: sat-token
          mountPath: /app/secrets
          readOnly: true
      volumes:
      - name: ca-cert-file
        secret:
          secretName: test-ca
          items:
          - key: tls.crt
            path: cafile.crt
      - name: sat-token
        secret:
          secretName: sat-token-secret
          items:
          - key: token
            path: sat_token
