apiVersion: deviceregistry.microsoft.com/v1
kind: Asset
metadata:
  name: asset-public-https-anonymous-1-stream-to-rtsp-autostart
spec:
  assetEndpointProfileRef: aep-public-https-anonymous-1
  enabled: true
  datasets:
    - name: dataset1
      dataPoints:
        - name: stream-to-rtsp
          dataSource: stream-to-rtsp
          dataPointConfiguration: |-
            {
              "taskType": "stream-to-rtsp",
              "autostart": true,
              "realtime": true,
              "loop": true
            }
