apiVersion: deviceregistry.microsoft.com/v1
kind: Asset
metadata:
  name: asset-public-http-anonymous-1-clip-to-fs-autostart
spec:
  assetEndpointProfileRef: aep-public-http-anonymous-1
  enabled: true
  datasets:
    - name: dataset1
      dataPoints:
        - name: clip-to-fs
          dataSource: clip-to-fs
          dataPointConfiguration: |-
            {
              "taskType": "clip-to-fs",
              "format": "avi",
              "autostart": true,
              "realtime": true,
              "loop": true,
              "duration": 3
            }
