apiVersion: deviceregistry.microsoft.com/v1
kind: Asset
metadata:
  name: asset-public-http-anonymous-1-clip-to-mqtt-noautostart
spec:
  assetEndpointProfileRef: aep-public-http-anonymous-1
  datasets:
    - name: dataset1
      dataPoints:
        - name: clip-to-mqtt
          dataSource: clip-to-mqtt
          dataPointConfiguration: |-
            {
              "taskType": "clip-to-mqtt",
              "format": "avi",
              "autostart": false,
              "realtime": true,
              "loop": true,
              "fps": 3,
              "audioEnabled": false,
              "duration": 3
            }
