apiVersion: v1
kind: Namespace
metadata:
  name: azure-arc
  labels:
    app.kubernetes.io/managed-by: Helm
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
  annotations:
    meta.helm.sh/release-name: azure-arc
    meta.helm.sh/release-namespace: azure-arc-release
--- 
apiVersion: v1
kind: Namespace
metadata:
  name: arc-workload-identity
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
--- 
apiVersion: v1
kind: Namespace
metadata:
  name: azure-arc-containerstorage
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
--- 
apiVersion: v1
kind: Namespace
metadata:
  name: azure-arc-acstor
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
--- 
apiVersion: v1
kind: Namespace
metadata:
  name: azure-extensions-usage-system
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
--- 
apiVersion: v1
kind: Namespace
metadata:
  name: azure-secret-store
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
--- 
apiVersion: v1
kind: Namespace
metadata:
  name: azure-iot-operations
  labels:
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
 