# Important: This listener will enable an open MQTT port to facilitate development and testing.
# Do not use in production environments.
apiVersion: mqttbroker.iotoperations.azure.com/v1beta1
kind: BrokerListener
metadata:
  name: az-mqtt-non-tls-listener
  namespace: azure-iot-operations
spec:
  brokerRef: broker
  ports:
  - port: 1883
  serviceName: aio-mq-dmqtt-frontend-nontls
  serviceType: loadBalancer
