apiVersion: connectivity.iotoperations.azure.com/v1beta1
kind: DataflowEndpoint
metadata:
  name: mq-source
  namespace: azure-iot-operations
spec:
  endpointType: mqttSettings
  mqttSettings:
    host: "aio-mq-dmqtt-frontend:8883"
    tls:
      mode: Enabled
      # NOTE this is where we put the server cert configmap value
      trustedCaCertificateConfigMapRef: aio-ca-trust-bundle-test-only
  authentication:
    method: ServiceAccountToken
    serviceAccountTokenSettings:
      audience: aio-mq
---
apiVersion: connectivity.iotoperations.azure.com/v1beta1
kind: DataflowEndpoint
metadata:
  name: kafka-target
  namespace: azure-iot-operations
spec:
  endpointType: kafkaSettings
  kafkaSettings:
    host: "<NAMESPACE>.servicebus.windows.net:9093"
    batching:
      latencyMs: 0
      maxMessages: 100
    tls:
      mode: Enabled
  authentication:
    method: SystemAssignedManagedIdentity
    systemAssignedManagedIdentitySettings:
      # Don't forget the https://
      audience: https://<NAMESPACE>.servicebus.windows.net
---
apiVersion: connectivity.iotoperations.azure.com/v1beta1
kind: Dataflow
metadata:
  name: mq-to-kafka
  namespace: azure-iot-operations
spec:
  profileRef: example-dataflow
  operations:
    - operationType: source
      sourceSettings:
        endpointRef: mq-source
        dataSources:
        - azure-iot-operations/data/#
    - operationType: destination
      destinationSettings:
        endpointRef: kafka-target
        dataDestination: destinationeh
---
apiVersion: connectivity.iotoperations.azure.com/v1beta1
kind: DataflowProfile
metadata:
  name: example-dataflow
  namespace: azure-iot-operations
spec:
  instanceCount: 1
  diagnostics:
    logs:
      level: "debug"