# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: iotoperations-pubsub
  namespace: azure-iot-operations
  annotations:
    dapr.io/component-container: >
      {
        "name": "iot-operations-dapr-components",
        "image": "ghcr.io/azure/iot-operations-dapr-components:latest",
        "volumeMounts": [
          { "name": "mqtt-client-token", "mountPath": "/var/run/secrets/tokens" },
          { "name": "aio-ca-trust-bundle", "mountPath": "/var/run/certs/aio-mq-ca-cert" }
        ]
      }
spec:
  type: pubsub.azure.iotoperations
  version: v1
  metadata:
  - name: hostname
    value: aio-mq-dmqtt-frontend
  - name: tcpPort
    value: 8883
  - name: useTls
    value: true
  - name: caFile
    value: /var/run/certs/aio-mq-ca-cert/ca.crt
  - name: satAuthFile
    value: /var/run/secrets/tokens/mqtt-client-token
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: iotoperations-statestore
  namespace: azure-iot-operations
spec:
  type: state.azure.iotoperations
  version: v1
  metadata:
  - name: hostname
    value: aio-mq-dmqtt-frontend
  - name: tcpPort
    value: 8883
  - name: useTls
    value: true
  - name: caFile
    value: /var/run/certs/aio-mq-ca-cert/ca.crt
  - name: satAuthFile
    value: /var/run/secrets/tokens/mqtt-client-token
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: servicebus-binding
  namespace: azure-iot-operations
spec:
  type: bindings.azure.servicebusqueues
  version: v1
  metadata:
  - name: connectionString
    value: "{connectionString}" # Insert your Service Bus connection string here
  - name: queueName
    value: "{queueName}"        # Insert the Service bus queue name here
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dapr-client
  namespace: azure-iot-operations
  annotations:
    aio-mq-broker-auth/group: dapr-workload
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-workload-service-bus-dotnet
  namespace: azure-iot-operations
spec:
  selector:
    matchLabels:
      app: dapr-workload-service-bus-dotnet
  template:
    metadata:
      labels:
        app: dapr-workload-service-bus-dotnet
      annotations:
        dapr.io/enabled: "true"
        dapr.io/inject-pluggable-components: "true"
        dapr.io/app-id: "dapr-workload-service-bus-dotnet"
        dapr.io/app-port: "6001"
        dapr.io/app-protocol: "http"
    spec:
      serviceAccountName: dapr-client
      volumes:
        - name: mqtt-client-token
          projected:
            sources:
              - serviceAccountToken:
                  path: mqtt-client-token
                  audience: aio-mq
                  expirationSeconds: 86400    
        - name: aio-ca-trust-bundle
          configMap:
            name: aio-ca-trust-bundle-test-only
      containers:
      - name: dapr-workload-service-bus-dotnet
        image: dapr-service-bus-dotnet
        imagePullPolicy: Never
