apiVersion: mqttbroker.iotoperations.azure.com/v1
kind: BrokerListener
metadata:
  name: aio-broker-notls
  namespace: azure-iot-operations
spec:
  brokerRef: default
  serviceType: LoadBalancer
  ports:
  - port: 1883
    protocol: Mqtt

---

apiVersion: v1
kind: Service
metadata:
  name: aio-broker-notls
  namespace: azure-iot-operations
spec:
  type: LoadBalancer
  ports:
  - port: 1883
    targetPort: 1883
