metrics:
  type: prometheus
  port: 2114
logLevel: 0
simulation:
  target:
    host: aio-mq-dmqtt-frontend
    port: 1883
  sites:
    - name: site0
      mqttVersion: v5
      assetCount: 1
      tags:
        - id: float_1
          configuration: x
          count: 1
      rate:
        messagesPerPeriod: 1
        periodSeconds: 1
        tagsPerMessage: 2
      payloadFormat: OPCUA
      topicFormat: /{{.SiteName}}/{{.AssetName}}
