---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: azure-iot-operations
  name: callout-conf
data:
  config.yml: |-
    logger:
      level: 0
    servers:
      http:
        port: 3333
        resources:
          - path: /example
            method: GET
            status: 200
            outputs: ["output1"]
            response: |
              {
                "hello": "world"
              }
          - path: /ref_data
            method: GET
            status: 200
            outputs: ["output1"]
            response: |
              [
                {
                  "assetID": "Sea_O1",
                  "serialNumber": "SN001",
                  "name": "Contoso",
                  "site": "Seattle",
                  "maintenanceStatus": "Done"
                },
                {
                  "assetID": "Red_O1",
                  "serialNumber": "SN002",
                  "name": "Contoso",
                  "site": "Redmond",
                  "maintenanceStatus": "Upcoming"
                },
                {
                  "assetID": "Tac_O1",
                  "serialNumber": "SN003",
                  "name": "Contoso",
                  "site": "Tacoma",
                  "maintenanceStatus": "Overdue"
                },
                {
                  "assetID": "Sea_S1",
                  "serialNumber": "SN004",
                  "name": "Contoso",
                  "site": "Seattle",
                  "maintenanceStatus": "Done"
                },
                {
                  "assetID": "Red_S1",
                  "serialNumber": "SN005",
                  "name": "Contoso",
                  "site": "Redmond",
                  "maintenanceStatus": "Done"
                },
                {
                  "assetID": "Sea_M1",
                  "serialNumber": "SN007",
                  "name": "Contoso",
                  "site": "Seattle",
                  "maintenanceStatus": "Done"
                },
                {
                  "assetID": "Red_M1",
                  "serialNumber": "SN008",
                  "name": "Contoso",
                  "site": "Redmond",
                  "maintenanceStatus": "Overdue"
                },
                {
                  "assetID": "Tac_M1",
                  "serialNumber": "SN009",
                  "name": "Contoso",
                  "site": "Tacoma",
                  "maintenanceStatus": "Done"
                },
                {
                  "assetID": "Tac_S1",
                  "serialNumber": "SN010",
                  "name": "Contoso",
                  "site": "Tacoma",
                  "maintenanceStatus": "Upcoming"
                }
              ]
          - path: /ts
            method: GET
            status: 200
            outputs: ["output1"]
            response: |
              {
                "timestamp": "2023-11-16T8:18:10-08:00"
              }
          - path: /productionData
            method: GET
            status: 200
            outputs: ["output1"]
            response: |
              [
                  {
                      "Line":"Line1",
                      "ProductId":"Bagel",
                      "Customer":"Contoso",
                      "Manufacturer": "Fabrikam"
                  },
                  {
                      "Line":"Line2",
                      "ProductId":"Donut",
                      "Customer":"Contoso",
                      "Manufacturer": "Northwind"
                  }
              ]
          - path: /operatorData
            method: GET
            status: 200
            outputs: ["output1"]
            response: |
              [
                  {
                      "Shift":0,
                      "Operator":"Bob",
                      "PerformanceTarget":45,
                      "PackagedProductTarget":12960
                  },
                  {
                      "Shift":1,
                      "Operator":"Anne",
                      "PerformanceTarget":60,
                      "PackagedProductTarget":17280
                  },
                  {
                      "Shift":2,
                      "Operator":"Cameron",
                      "PerformanceTarget":50,
                      "PackagedProductTarget":14400
                  }
              ]
      grpc:
        port: 3334
        outputs: ["output1"]
    outputs:
      - name: output1
        type: stdout
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: azure-iot-operations
  name: http-grpc-callout
  labels:
    app: http-grpc-callout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-grpc-callout
  template:
    metadata:
      labels:
        app: http-grpc-callout
    spec:
      containers:
        - name: http-grpc-callout
          image: ghcr.io/azure-samples/explore-iot-operations/http-grpc-callout:latest
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 3333
          - name: grpc
            containerPort: 3334
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          command:
            - "./bin/http-grpc-callout"
            - "--stdin=false"
            - "--config=/etc/http-grpc-callout/config.yml"
          volumeMounts:
            - mountPath: /etc/http-grpc-callout/config.yml
              subPath: config.yml
              name: config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: callout-conf
---
apiVersion: v1
kind: Service
metadata:
  namespace: azure-iot-operations
  name: callout-svc-http
  labels:
    app: http-grpc-callout
spec:
  ports:
  - port: 3333
    name: http
  type: ClusterIP
  selector:
    app: http-grpc-callout
---
apiVersion: v1
kind: Service
metadata:
  namespace: azure-iot-operations
  name: callout-svc-grpc
  labels:
    app: http-grpc-callout
spec:
  ports:
  - port: 3334
    name: grpc
  type: ClusterIP
  selector:
    app: http-grpc-callout
