# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: aio-mq-pubsub
  namespace: azure-iot-operations
  annotations:
    dapr.io/component-container: >
      {
        "name": "aio-mq-components",
        "image": "ghcr.io/azure/iot-mq-dapr-components:latest",
        "volumeMounts": [
          { "name": "mqtt-client-token", "mountPath": "/var/run/secrets/tokens" },
          { "name": "aio-ca-trust-bundle", "mountPath": "/var/run/certs/aio-mq-ca-cert" }
        ]
      }
spec:
  type: pubsub.aio-mq-pubsub-pluggable # DO NOT CHANGE
  version: v1
  metadata:
  - name: url
    value: aio-mq-dmqtt-frontend
  - name: port
    value: 8883
  - name: satTokenPath
    value: "/var/run/secrets/tokens/mqtt-client-token"
  - name: caCertPath
    value: "/var/run/certs/aio-mq-ca-cert/ca.crt"
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: aio-mq-statestore
  namespace: azure-iot-operations
spec:
  type: state.aio-mq-statestore-pluggable # DO NOT CHANGE
  version: v1
  metadata:
  - name: url
    value: aio-mq-dmqtt-frontend
  - name: port
    value: 8883  
  - name: satTokenPath
    value: "/var/run/secrets/tokens/mqtt-client-token"
  - name: caCertPath
    value: "/var/run/certs/aio-mq-ca-cert/ca.crt"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dapr-client
  namespace: azure-iot-operations
  annotations:
    aio-mq-broker-auth/group: dapr-workload
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dapr-workflow-sample
  namespace: azure-iot-operations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dapr-workflow-sample
  template:
    metadata:
      labels:
        app: dapr-workflow-sample
      annotations:
        dapr.io/enabled: "true"
        dapr.io/inject-pluggable-components: "true"
        dapr.io/app-id: "dapr-workflow-sample"
        dapr.io/app-port: "6001"
        dapr.io/app-protocol: "grpc"
    spec:
      serviceAccountName: dapr-client
      volumes:
      - name: mqtt-client-token
        projected:
          sources:
            - serviceAccountToken:
                path: mqtt-client-token
                audience: aio-mq
                expirationSeconds: 86400    
      - name: aio-ca-trust-bundle
        configMap:
            name: aio-ca-trust-bundle-test-only
      containers:
      - name: dapr-workload-sample
        image: dapr-workflow-sample
        imagePullPolicy: Never
