# Pub/sub component
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: aio-mq-pubsub
spec:
  type: pubsub.aio-mq-pubsub-pluggable # DO NOT CHANGE
  version: v1
  metadata:
  - name: url
    value: "aio-mq-dmqtt-frontend:8883"
  - name: satTokenPath
    value: "/var/run/secrets/tokens/mqtt-client-token"
  - name: tlsEnabled
    value: true
  - name: caCertPath
    value: "/var/run/certs/aio-mq-ca-cert/ca.crt"
  - name: logLevel
    value: "Info"
---
# State Management component
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: aio-mq-statestore
spec:
  type: state.aio-mq-statestore-pluggable # DO NOT CHANGE
  version: v1
  metadata:
  - name: url
    value: "aio-mq-dmqtt-frontend:8883"
  - name: satTokenPath
    value: "/var/run/secrets/tokens/mqtt-client-token"
  - name: tlsEnabled
    value: true
  - name: caCertPath
    value: "/var/run/certs/aio-mq-ca-cert/ca.crt"
  - name: logLevel
    value: "Info"