<#
.SYNOPSIS
    Azure IoT Operations - External Configurator (PowerShell)

.DESCRIPTION
    This script connects edge K3s clusters to Azure Arc and deploys Azure IoT Operations.
    It runs on a Windows management machine with Azure CLI and deploys infrastructure 
    using ARM templates for Infrastructure as Code (IaC).
    
    Requirements:
    - Windows 10/11 or Windows Server 2019+
    - PowerShell 7+ (recommended; 5.1 will produce a warning)
    - Azure CLI 2.64.0+ with iot-ops extension
    - Azure credentials with appropriate permissions
    - cluster_info.json from installer.sh (optional; AKS-EE / single-machine users can skip it)
    - For a zero-JSON quickstart, run session-bootstrap.ps1 first to pre-load env vars
    
.PARAMETER ConfigFile
    Path to configuration file (default: config/aio_config.json)
    
.PARAMETER ClusterInfo
    Path to cluster_info.json file generated by installer.sh (default: config/cluster_info.json)
    
.PARAMETER DryRun
    Validate configuration and show what-if without making changes
    
.PARAMETER SkipIoTOps
    Skip Azure IoT Operations deployment (deploy infrastructure only)

.PARAMETER SkipVerification
    Skip post-deployment verification

.PARAMETER DemoMode
    Use low-resource MQTT broker settings (~303 MiB RAM instead of ~15.8 GB default).
    Intended for laptops and single-machine AKS-EE demos. Not suitable for production.
    Applies: --broker-frontend-replicas 1 --broker-frontend-workers 1 --broker-backend-part 1
             --broker-backend-rf 2 --broker-backend-workers 1 --broker-mem-profile Tiny
    
.EXAMPLE
    .\External-Configurator.ps1
    
.EXAMPLE
    .\External-Configurator.ps1 -DryRun
    
.NOTES
    Author: Azure IoT Operations Team
    Date: January 2026
    Version: 2.0.0 - ARM Template Based Deployment
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory=$false)]
    [string]$ConfigFile = "",
    
    [Parameter(Mandatory=$false)]
    [string]$ClusterInfo = "",
    
    [Parameter(Mandatory=$false)]
    [switch]$DryRun,
    
    [Parameter(Mandatory=$false)]
    [switch]$SkipIoTOps,
    
    [Parameter(Mandatory=$false)]
    [switch]$SkipVerification,

    [Parameter(Mandatory=$false)]
    [switch]$DemoMode
)

# ============================================================================
# GLOBAL VARIABLES
# ============================================================================

$script:ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$script:RepoRoot = Split-Path -Parent $script:ScriptDir
$script:ConfigDir = Join-Path $script:RepoRoot "config"
$script:ArmTemplatesDir = Join-Path $script:RepoRoot "arm_templates"
$script:LogFile = Join-Path $script:ScriptDir "external_configurator_$(Get-Date -Format 'yyyyMMdd_HHmmss').log"
$script:DeploymentSummaryFile = Join-Path $script:ConfigDir "deployment_summary.yaml"

# Configuration variables (loaded from files)
$script:ClusterData = $null
$script:AzureConfig = $null
$script:SubscriptionId = $null
$script:SubscriptionName = $null
$script:ResourceGroup = $null
$script:Location = $null
$script:ClusterName = $null
$script:ConfigClusterName = $null  # Cluster name from aio_config.json (for validation)
$script:NamespaceName = $null
$script:KeyVaultName = $null
$script:StorageAccountName = $null
$script:SchemaRegistryName = $null
$script:ContainerRegistryName = $null        # Short name (e.g. myregistry)
$script:ContainerRegistryLoginServer = $null # Login server (e.g. myregistry.azurecr.io)
$script:UserObjectId = $null  # Current user's Entra ID object ID for Key Vault access

# Deployment tracking
$script:DeployedResources = @()
$script:Errors = @()

# ============================================================================
# LOGGING FUNCTIONS
# ============================================================================

function Initialize-Logging {
    Start-Transcript -Path $script:LogFile -Append
    
    Write-Host "============================================================================" -ForegroundColor Cyan
    Write-Host "Azure IoT Operations - External Configurator v2.0" -ForegroundColor Cyan
    Write-Host "ARM Template Based Deployment" -ForegroundColor Cyan
    Write-Host "============================================================================" -ForegroundColor Cyan
    Write-Host "Log file: $script:LogFile" -ForegroundColor Gray
    Write-Host "Started: $(Get-Date)" -ForegroundColor Gray
    Write-Host "Script directory: $script:ScriptDir" -ForegroundColor Gray
    Write-Host "ARM templates: $script:ArmTemplatesDir" -ForegroundColor Gray
    Write-Host ""
    
    if ($DryRun) {
        Write-Warning "RUNNING IN DRY-RUN MODE - Will use what-if validation only"
        Write-Host ""
    }
}

function Write-Log {
    param([string]$Message)
    $timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    Write-Host "[${timestamp}] $Message" -ForegroundColor Green
}

function Write-InfoLog {
    param([string]$Message)
    $timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    Write-Host "[${timestamp}] INFO: $Message" -ForegroundColor Cyan
}

function Write-WarnLog {
    param([string]$Message)
    $timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    Write-Warning "[${timestamp}] WARNING: $Message"
}

function Write-ErrorLog {
    param(
        [string]$Message,
        [switch]$Fatal
    )
    $timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    Write-Host "[${timestamp}] ERROR: $Message" -ForegroundColor Red
    
    $script:Errors += $Message
    
    if ($Fatal) {
        Write-Host ""
        Write-Host "Fatal error encountered. Exiting." -ForegroundColor Red
        Write-Host "Check log file for details: $script:LogFile" -ForegroundColor Yellow
        Stop-Transcript
        exit 1
    }
}

function Write-Success {
    param([string]$Message)
    $timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    Write-Host "[${timestamp}] SUCCESS: $Message" -ForegroundColor Green
}

# ============================================================================
# PREREQUISITE CHECKS
# ============================================================================

function Test-Prerequisites {
    Write-Log "Checking prerequisites..."
    
    $allPassed = $true
    
    # Check PowerShell version
    $psVersion = $PSVersionTable.PSVersion
    if ($psVersion.Major -lt 7) {
        Write-WarnLog "PowerShell 7+ is recommended. Current version: $psVersion"
        Write-WarnLog "Some features may not work correctly. Download PS7: https://aka.ms/install-powershell"
        Write-WarnLog "Continuing, but errors may occur."
    } else {
        Write-Success "PowerShell version: $psVersion"
    }
    
    # Check if Azure CLI is installed
    try {
        $azVersion = az version --output json 2>$null | ConvertFrom-Json
        $azCliVersion = $azVersion.'azure-cli'
        Write-Success "Azure CLI version: $azCliVersion"

        # Check minimum version 2.64.0
        $minVersion = [Version]"2.64.0"
        $currentAzVersion = [Version]$azCliVersion
        if ($currentAzVersion -lt $minVersion) {
            Write-WarnLog "Azure CLI $azCliVersion is below the recommended minimum 2.64.0."
            Write-WarnLog "This may cause deployment failures. Upgrade with: az upgrade"
            Write-WarnLog "Or reinstall from: https://aka.ms/installazurecliwindows"
            Write-WarnLog "Continuing, but errors may occur."
        }
    } catch {
        Write-ErrorLog "Azure CLI is not installed or not in PATH" -Fatal
    }
    
    # Check for iot-ops extension
    $extensions = az extension list --output json 2>$null | ConvertFrom-Json
    $iotOpsExt = $extensions | Where-Object { $_.name -eq 'azure-iot-ops' }
    
    if (-not $iotOpsExt) {
        Write-WarnLog "azure-iot-ops extension not found. Install it manually before continuing:"
        Write-WarnLog "  az extension add --name azure-iot-ops --upgrade"
        Write-WarnLog "Then re-run this script."
        $allPassed = $false
    } else {
        Write-Success "azure-iot-ops extension version: $($iotOpsExt.version)"
    }
    
    # Check ARM templates directory
    if (-not (Test-Path $script:ArmTemplatesDir)) {
        Write-ErrorLog "ARM templates directory not found: $script:ArmTemplatesDir" -Fatal
    }
    Write-Success "ARM templates directory found"
    
    # Check config directory
    if (-not (Test-Path $script:ConfigDir)) {
        Write-ErrorLog "Config directory not found: $script:ConfigDir" -Fatal
    }
    Write-Success "Config directory found"
    
    if (-not $allPassed) {
        Write-ErrorLog "Prerequisite checks failed" -Fatal
    }
    
    Write-Success "All prerequisites passed"
}

# ============================================================================
# CONFIGURATION LOADING
# ============================================================================

function Import-ClusterInfo {
    Write-Log "Loading cluster information..."
    
    # Determine cluster info path
    $clusterInfoPath = $null
    
    if ($ClusterInfo) {
        if ([System.IO.Path]::IsPathRooted($ClusterInfo)) {
            $clusterInfoPath = $ClusterInfo
        } else {
            $clusterInfoPath = Join-Path $script:ScriptDir $ClusterInfo
        }
    } else {
        # Default: look in config folder
        $clusterInfoPath = Join-Path $script:ConfigDir "cluster_info.json"
    }
    
    if (-not (Test-Path $clusterInfoPath)) {
        Write-WarnLog "Cluster info file not found: $clusterInfoPath"
        Write-Host ""
        Write-Host "cluster_info.json is optional." -ForegroundColor Yellow
        Write-Host "  - AKS-EE / single-machine users: continue without it (cluster name comes from config/env)." -ForegroundColor Gray
        Write-Host "  - K3s edge device users: copy config/cluster_info.json from your edge device to: $script:ConfigDir" -ForegroundColor Gray
        Write-Host ""
        $script:ClusterData = $null
        return
    }
    
    try {
        $script:ClusterData = Get-Content $clusterInfoPath -Raw | ConvertFrom-Json
        
        Write-Host ""
        Write-Host "Cluster Information:" -ForegroundColor Cyan
        Write-Host "  Cluster Name: $($script:ClusterData.cluster_name)" -ForegroundColor Gray
        Write-Host "  Node Name: $($script:ClusterData.node_name)" -ForegroundColor Gray
        Write-Host "  Node IP: $($script:ClusterData.node_ip)" -ForegroundColor Gray
        Write-Host "  Kubernetes Version: $($script:ClusterData.kubernetes_version)" -ForegroundColor Gray
        Write-Host "  Node OS: $($script:ClusterData.node_os)" -ForegroundColor Gray
        Write-Host "  Ready for Arc: $($script:ClusterData.ready_for_arc)" -ForegroundColor Gray
        Write-Host "  Installer Version: $($script:ClusterData.installer_version)" -ForegroundColor Gray
        Write-Host ""
        
        # Set cluster name from cluster info
        $script:ClusterName = $script:ClusterData.cluster_name
        
        Write-Success "Cluster information loaded from: $clusterInfoPath"
    } catch {
        Write-ErrorLog "Failed to parse cluster info file: $_" -Fatal
    }
}

function Import-AzureConfig {
    Write-Log "Loading Azure configuration..."
    
    # Determine config path
    $configPath = $null
    
    if ($ConfigFile) {
        if ([System.IO.Path]::IsPathRooted($ConfigFile)) {
            $configPath = $ConfigFile
        } else {
            $configPath = Join-Path $script:ScriptDir $ConfigFile
        }
    } else {
        # Default: look in config folder
        $configPath = Join-Path $script:ConfigDir "aio_config.json"
    }
    
    # Normalise env var aliases FIRST (before any early return) so they are available
    # regardless of whether a config file is found.
    # session-bootstrap.ps1 uses AZ_* / AKS_EDGE_* names; scripts check AZURE_* / AKSEDGE_*.
    if ([string]::IsNullOrEmpty($env:AZURE_SUBSCRIPTION_ID)    -and -not [string]::IsNullOrEmpty($env:AZ_SUBSCRIPTION_ID))    { $env:AZURE_SUBSCRIPTION_ID    = $env:AZ_SUBSCRIPTION_ID }
    if ([string]::IsNullOrEmpty($env:AZURE_RESOURCE_GROUP)     -and -not [string]::IsNullOrEmpty($env:AZ_RESOURCE_GROUP))     { $env:AZURE_RESOURCE_GROUP     = $env:AZ_RESOURCE_GROUP }
    if ([string]::IsNullOrEmpty($env:AZURE_LOCATION)           -and -not [string]::IsNullOrEmpty($env:AZ_LOCATION))           { $env:AZURE_LOCATION           = $env:AZ_LOCATION }
    if ([string]::IsNullOrEmpty($env:AKSEDGE_CLUSTER_NAME)     -and -not [string]::IsNullOrEmpty($env:AKS_EDGE_CLUSTER_NAME)) { $env:AKSEDGE_CLUSTER_NAME     = $env:AKS_EDGE_CLUSTER_NAME }
    if ([string]::IsNullOrEmpty($env:AZURE_CONTAINER_REGISTRY) -and -not [string]::IsNullOrEmpty($env:AZ_CONTAINER_REGISTRY)) { $env:AZURE_CONTAINER_REGISTRY = $env:AZ_CONTAINER_REGISTRY }

    Write-Host "[CONFIG] Looking for aio_config.json at: $configPath" -ForegroundColor Gray
    if (-not (Test-Path $configPath)) {
        Write-WarnLog "Config file not found: $configPath"
        Write-Host ""
        Write-Host "Configuration will be collected interactively." -ForegroundColor Yellow
        Write-Host "To use a config file, copy from template:" -ForegroundColor Yellow
        Write-Host "  cp config/quickstart_config.template config/aio_config.json" -ForegroundColor Gray
        Write-Host ""
    }
    
    try {
        $script:AzureConfig = Get-Content $configPath -Raw | ConvertFrom-Json
        
        # Load Azure settings
        if ($script:AzureConfig.azure) {
            $script:SubscriptionId = $script:AzureConfig.azure.subscription_id
            $script:ResourceGroup = $script:AzureConfig.azure.resource_group
            $script:Location = $script:AzureConfig.azure.location
            $rawNamespace = $script:AzureConfig.azure.namespace_name
            if ($rawNamespace) {
                $script:NamespaceName = $rawNamespace.ToLower()
                if ($script:NamespaceName -cne $rawNamespace) { Write-Warning "[CONFIG] namespace_name '$rawNamespace' was converted to lowercase: '$script:NamespaceName'" }
            }

            $rawStorage = $script:AzureConfig.azure.storage_account_name
            if ($rawStorage) {
                $script:StorageAccountName = $rawStorage.ToLower()
                if ($script:StorageAccountName -cne $rawStorage) { Write-Warning "[CONFIG] storage_account_name '$rawStorage' was converted to lowercase: '$script:StorageAccountName'" }
            }

            $rawKv = $script:AzureConfig.azure.key_vault_name
            if ($rawKv) {
                $script:KeyVaultName = $rawKv.ToLower()
                if ($script:KeyVaultName -cne $rawKv) { Write-Warning "[CONFIG] key_vault_name '$rawKv' was converted to lowercase: '$script:KeyVaultName'" }
            }
            
            # Store the config cluster name for validation (don't override yet)
            $script:ConfigClusterName = $script:AzureConfig.azure.cluster_name

            # Load container registry (either short name or login server)
            if ($script:AzureConfig.azure.PSObject.Properties['container_registry'] -and $script:AzureConfig.azure.container_registry) {
                $rawReg = $script:AzureConfig.azure.container_registry
                if ($rawReg -match '\.azurecr\.io$') {
                    $script:ContainerRegistryLoginServer = $rawReg
                    $script:ContainerRegistryName = $rawReg -replace '\.azurecr\.io$', ''
                } else {
                    $script:ContainerRegistryName = $rawReg
                    $script:ContainerRegistryLoginServer = "${rawReg}.azurecr.io"
                }
            }
        }
        
        Write-Success "Azure configuration loaded from: $configPath"
    } catch {
        Write-ErrorLog "Failed to parse config file: $_"
        Write-WarnLog "Configuration will be collected interactively"
    }

    # Step 2: Environment variables — only fill in values still empty after config file
    Write-Host "[CONFIG] Step 2: Environment variables (fallback for values missing from config)" -ForegroundColor Gray

    # Normalise aliases: session-bootstrap uses AZ_* / AKS_EDGE_* names; scripts use AZURE_* / AKSEDGE_*
    # Accept both so users don't have to know the difference.
    if (-not [string]::IsNullOrEmpty($env:AZURE_SUBSCRIPTION_ID)) {
        if ([string]::IsNullOrEmpty($script:SubscriptionId)) {
            $script:SubscriptionId = $env:AZURE_SUBSCRIPTION_ID
            Write-InfoLog "  [env] AZURE_SUBSCRIPTION_ID    = $script:SubscriptionId"
        } else { Write-InfoLog "  [env] AZURE_SUBSCRIPTION_ID    = (skipped - config file value used)" }
    } else { Write-InfoLog "  [env] AZURE_SUBSCRIPTION_ID    - not set" }

    if (-not [string]::IsNullOrEmpty($env:AZURE_RESOURCE_GROUP)) {
        if ([string]::IsNullOrEmpty($script:ResourceGroup)) {
            $script:ResourceGroup = $env:AZURE_RESOURCE_GROUP
            Write-InfoLog "  [env] AZURE_RESOURCE_GROUP     = $script:ResourceGroup"
        } else { Write-InfoLog "  [env] AZURE_RESOURCE_GROUP     = (skipped - config file value used)" }
    } else { Write-InfoLog "  [env] AZURE_RESOURCE_GROUP     - not set" }

    if (-not [string]::IsNullOrEmpty($env:AZURE_LOCATION)) {
        if ([string]::IsNullOrEmpty($script:Location)) {
            $script:Location = $env:AZURE_LOCATION
            Write-InfoLog "  [env] AZURE_LOCATION           = $script:Location"
        } else { Write-InfoLog "  [env] AZURE_LOCATION           = (skipped - config file value used)" }
    } else { Write-InfoLog "  [env] AZURE_LOCATION           - not set" }

    if (-not [string]::IsNullOrEmpty($env:AKSEDGE_CLUSTER_NAME)) {
        if ([string]::IsNullOrEmpty($script:ConfigClusterName)) {
            $script:ConfigClusterName = $env:AKSEDGE_CLUSTER_NAME
            if ([string]::IsNullOrEmpty($script:ClusterName)) { $script:ClusterName = $env:AKSEDGE_CLUSTER_NAME }
            Write-InfoLog "  [env] AKSEDGE_CLUSTER_NAME     = $script:ConfigClusterName"
        } else { Write-InfoLog "  [env] AKSEDGE_CLUSTER_NAME     = (skipped - config file value used)" }
    } else { Write-InfoLog "  [env] AKSEDGE_CLUSTER_NAME     - not set" }

    if (-not [string]::IsNullOrEmpty($env:AZURE_CONTAINER_REGISTRY)) {
        if ([string]::IsNullOrEmpty($script:ContainerRegistryName)) {
            $rawReg = $env:AZURE_CONTAINER_REGISTRY
            if ($rawReg -match '\.azurecr\.io$') {
                $script:ContainerRegistryLoginServer = $rawReg
                $script:ContainerRegistryName = $rawReg -replace '\.azurecr\.io$', ''
            } else {
                $script:ContainerRegistryName = $rawReg
                $script:ContainerRegistryLoginServer = "${rawReg}.azurecr.io"
            }
            Write-InfoLog "  [env] AZURE_CONTAINER_REGISTRY = $script:ContainerRegistryName"
        } else { Write-InfoLog "  [env] AZURE_CONTAINER_REGISTRY = (skipped - config file value used)" }
    } else { Write-InfoLog "  [env] AZURE_CONTAINER_REGISTRY - not set (will auto-generate)" }
}

function Test-ConfigConsistency {
    Write-Log "Validating configuration consistency..."

    # If cluster_info.json was not found (AKS-EE / single-machine workflow),
    # skip cross-validation and rely solely on aio_config.json / env vars.
    if ($null -eq $script:ClusterData) {
        if ($script:ConfigClusterName) {
            $script:ClusterName = $script:ConfigClusterName
            Write-InfoLog "cluster_info.json not loaded - cluster name from config/env: $script:ClusterName"
        } else {
            Write-WarnLog "No cluster_info.json and no cluster name in config or env vars."
            Write-WarnLog "You will be prompted for the cluster name during deployment."
        }
        return
    }

    # Check if both configs have cluster names defined
    $clusterInfoName = $script:ClusterData.cluster_name
    $aioConfigName = $script:ConfigClusterName
    
    if (-not $clusterInfoName) {
        Write-WarnLog "cluster_info.json was found but cluster_name is empty."
        Write-Host "  Falling back to env var / aio_config.json for cluster name." -ForegroundColor Yellow
        Write-Host "  (On the AKS-EE path this file is not required - safe to delete.)" -ForegroundColor Gray

        # 1. aio_config.json value already loaded into script:ConfigClusterName
        if ($script:ConfigClusterName) {
            $script:ClusterName = $script:ConfigClusterName
            Write-InfoLog "[CONFIG] Cluster name from aio_config.json: $script:ClusterName"
        # 2. Env var fallback
        } elseif ($env:AKSEDGE_CLUSTER_NAME) {
            $script:ClusterName = $env:AKSEDGE_CLUSTER_NAME
            Write-InfoLog "[ENV] Cluster name from AKSEDGE_CLUSTER_NAME: $script:ClusterName"
        # 3. Prompt as last resort
        } else {
            Write-Warning "[INPUT] AKSEDGE_CLUSTER_NAME not found in env vars or config."
            $script:ClusterName = Read-Host "Enter Cluster name"
            $env:AKSEDGE_CLUSTER_NAME = $script:ClusterName
            Write-Host "[INPUT] Saved as `$env:AKSEDGE_CLUSTER_NAME for this session." -ForegroundColor Cyan
        }
        $script:ClusterData = $null  # treat as not loaded
        return
    }
    
    if (-not $aioConfigName) {
        Write-InfoLog "aio_config.json does not specify cluster_name - using cluster_info.json value: $clusterInfoName"
        $script:ClusterName = $clusterInfoName
        return
    }
    
    # Both have cluster names - check if they match
    if ($clusterInfoName -ne $aioConfigName) {
        Write-Host ""
        Write-Host "============================================================================" -ForegroundColor Red
        Write-Host "WARNING: Cluster name mismatch detected!" -ForegroundColor Red
        Write-Host "============================================================================" -ForegroundColor Red
        Write-Host ""
        Write-Host "  cluster_info.json (from edge installer): $clusterInfoName" -ForegroundColor Yellow
        Write-Host "  aio_config.json (Azure config):          $aioConfigName" -ForegroundColor Yellow
        Write-Host ""
        Write-Host "This could indicate:" -ForegroundColor Cyan
        Write-Host "  - You're using the wrong config file for this cluster" -ForegroundColor Gray
        Write-Host "  - The aio_config.json was not updated after a fresh edge install" -ForegroundColor Gray
        Write-Host "  - These configs are for different environments" -ForegroundColor Gray
        Write-Host ""
        Write-Host "The cluster_info.json name comes from the actual edge device installer." -ForegroundColor Cyan
        Write-Host "The aio_config.json name is what will be used for Azure Arc registration." -ForegroundColor Cyan
        Write-Host ""
        
        Write-Host "Options:" -ForegroundColor Cyan
        Write-Host "  [1] Use cluster_info.json value: $clusterInfoName (recommended for fresh installs)" -ForegroundColor Gray
        Write-Host "  [2] Use aio_config.json value: $aioConfigName (if cluster is already Arc-enabled with this name)" -ForegroundColor Gray
        Write-Host "  [3] Abort and fix the configuration files" -ForegroundColor Gray
        Write-Host ""
        
        $choice = Read-Host "Enter choice (1/2/3)"
        
        switch ($choice) {
            "1" {
                $script:ClusterName = $clusterInfoName
                Write-InfoLog "Using cluster name from cluster_info.json: $clusterInfoName"
                Write-WarnLog "Consider updating aio_config.json to match: cluster_name = '$clusterInfoName'"
            }
            "2" {
                $script:ClusterName = $aioConfigName
                Write-InfoLog "Using cluster name from aio_config.json: $aioConfigName"
                Write-WarnLog "Consider updating cluster_info.json if this is a fresh install"
            }
            "3" {
                Write-Host ""
                Write-Host "To fix this, update one of the files to match:" -ForegroundColor Yellow
                Write-Host "  - Edit config/aio_config.json and set cluster_name to '$clusterInfoName'" -ForegroundColor Gray
                Write-Host "  - Or edit config/cluster_info.json and set cluster_name to '$aioConfigName'" -ForegroundColor Gray
                Write-Host ""
                Write-ErrorLog "Configuration mismatch - user chose to abort" -Fatal
            }
            default {
                Write-ErrorLog "Invalid choice. Aborting." -Fatal
            }
        }
    } else {
        Write-Success "Cluster names match: $clusterInfoName"
        $script:ClusterName = $clusterInfoName
    }
}

function Test-RequiredVariables {
    Write-Log "Validating required configuration..."

    $varHelp = @{
        "ResourceGroup" = @{ Env = "AZURE_RESOURCE_GROUP"; Label = "Azure resource group name" }
        "ClusterName"   = @{ Env = "AKSEDGE_CLUSTER_NAME"; Label = "Arc-enabled cluster name"  }
        "Location"      = @{ Env = "AZURE_LOCATION";       Label = "Azure region (e.g. eastus2)" }
    }

    $missingRequired = [System.Collections.Generic.List[string]]::new()
    if ([string]::IsNullOrEmpty($script:ResourceGroup)) { $missingRequired.Add("ResourceGroup") }
    if ([string]::IsNullOrEmpty($script:ClusterName))   { $missingRequired.Add("ClusterName") }
    if ([string]::IsNullOrEmpty($script:Location))      { $missingRequired.Add("Location") }

    if ($missingRequired.Count -eq 0) {
        Write-Success "All required variables present"
        Write-InfoLog "  Resource Group : $script:ResourceGroup"
        Write-InfoLog "  Cluster Name   : $script:ClusterName"
        Write-InfoLog "  Location       : $script:Location"
        return
    }

    Write-Host ""
    Write-Host ("=" * 60) -ForegroundColor Yellow
    Write-Host "REQUIRED CONFIGURATION MISSING" -ForegroundColor Yellow
    Write-Host ("=" * 60) -ForegroundColor Yellow
    Write-Host "The following values were not found in aio_config.json" -ForegroundColor Yellow
    Write-Host "or environment variables:" -ForegroundColor Yellow
    Write-Host ""
    foreach ($var in $missingRequired) {
        Write-Host "  - $($varHelp[$var].Label)" -ForegroundColor Red
        Write-Host "    set via: `$env:$($varHelp[$var].Env) = `"your-value`"" -ForegroundColor Gray
    }
    Write-Host ""
    Write-Host "Options to fix this without prompting:" -ForegroundColor Cyan
    Write-Host '  Option A  env vars:   $env:AZURE_RESOURCE_GROUP = "rg-my-iot"' -ForegroundColor White
    Write-Host '                         $env:AKSEDGE_CLUSTER_NAME = "my-cluster"' -ForegroundColor White
    Write-Host '                         $env:AZURE_LOCATION       = "eastus2"' -ForegroundColor White
    Write-Host "  Option B  config file: config/aio_config.json  (azure.resource_group, azure.cluster_name, azure.location)" -ForegroundColor White
    Write-Host "  Option C  CLI param:   -ConfigFile path/to/aio_config.json" -ForegroundColor White
    Write-Host ""

    foreach ($var in $missingRequired) {
        $value = Read-Host "  Enter $($varHelp[$var].Label)"
        if ([string]::IsNullOrWhiteSpace($value)) {
            Write-Host ""
            Write-ErrorLog "No value provided for $var. Cannot continue." -Fatal
        }
        switch ($var) {
            "ResourceGroup" { $script:ResourceGroup = $value.Trim() }
            "ClusterName"   { $script:ClusterName   = $value.Trim() }
            "Location"      { $script:Location      = $value.Trim() }
        }
    }

    # Final guard
    $stillMissing = @()
    if ([string]::IsNullOrEmpty($script:ResourceGroup)) { $stillMissing += "ResourceGroup  (env: AZURE_RESOURCE_GROUP)" }
    if ([string]::IsNullOrEmpty($script:ClusterName))   { $stillMissing += "ClusterName    (env: AKSEDGE_CLUSTER_NAME)" }
    if ([string]::IsNullOrEmpty($script:Location))      { $stillMissing += "Location       (env: AZURE_LOCATION)" }
    if ($stillMissing.Count -gt 0) {
        Write-Host ""
        foreach ($v in $stillMissing) { Write-ErrorLog "  Missing: $v" }
        Write-ErrorLog "Cannot continue - required configuration still missing." -Fatal
    }
}

# ============================================================================
# AZURE AUTHENTICATION
# ============================================================================

function Connect-ToAzure {
    Write-Log "Checking Azure authentication..."
    
    # Check if already logged in
    try {
        $currentAccount = az account show 2>$null | ConvertFrom-Json
        if ($currentAccount) {
            Write-Success "Already logged in as: $($currentAccount.user.name)"
            Write-InfoLog "Subscription: $($currentAccount.name)"
        }
    } catch {
        Write-Log "Not currently logged into Azure. Initiating login..."
        
        if ($DryRun) {
            Write-InfoLog "[DRY-RUN] Would execute: az login"
            return
        }
        
        az login
        $currentAccount = az account show | ConvertFrom-Json
    }
    
    # Set subscription if specified
    if ($script:SubscriptionId) {
        $currentSubId = $currentAccount.id
        if ($script:SubscriptionId -ne $currentSubId) {
            Write-Log "Setting subscription to: $script:SubscriptionId"
            
            if (-not $DryRun) {
                az account set --subscription $script:SubscriptionId
            }
        }
    }
    
    # Get final subscription details
    $currentAccount = az account show | ConvertFrom-Json
    $script:SubscriptionId = $currentAccount.id
    $script:SubscriptionName = $currentAccount.name

    if (-not $script:NamespaceName) {
        $script:NamespaceName = "$($script:ClusterName)-ns".ToLower()
        Write-InfoLog "Using default namespace name: $script:NamespaceName"
    }
    
    # Generate resource names if not provided
    $clusterNameClean = $script:ClusterName.ToLower() -replace '[^a-z0-9]', ''
    if ($clusterNameClean -cne $script:ClusterName) { Write-Warning "[NAME] Cluster name '$($script:ClusterName)' was sanitized to '$clusterNameClean' for use in resource names (lowercase, alphanumeric only)" }
    
    if (-not $script:StorageAccountName) {
        $script:StorageAccountName = ($clusterNameClean + "storage").Substring(0, [Math]::Min(24, ($clusterNameClean + "storage").Length))
        Write-InfoLog "Using auto-generated storage account name: $script:StorageAccountName"
    }
    
    if (-not $script:SchemaRegistryName) {
        $script:SchemaRegistryName = "$($script:ClusterName)-schema-registry".ToLower()
        Write-InfoLog "Using auto-generated schema registry name: $script:SchemaRegistryName"
    }

    if (-not $script:ContainerRegistryName) {
        # ACR names: 5-50 chars, alphanumeric only, globally unique
        $script:ContainerRegistryName = ($clusterNameClean + "acr").Substring(0, [Math]::Min(50, ($clusterNameClean + "acr").Length))
        $script:ContainerRegistryLoginServer = "$($script:ContainerRegistryName).azurecr.io"
        Write-InfoLog "Using auto-generated container registry name: $script:ContainerRegistryName"
    }
    
    if (-not $script:KeyVaultName) {
        # Generate deterministic Key Vault name from resource group (for idempotency)
        # Key Vault names must be 3-24 chars, alphanumeric and hyphens only
        $rgClean = $script:ResourceGroup.ToLower() -replace '[^a-z0-9]', ''
        if ($rgClean -cne $script:ResourceGroup) { Write-Warning "[NAME] Resource group '$($script:ResourceGroup)' was sanitized to '$rgClean' for use in Key Vault name (lowercase, alphanumeric only)" }
        $script:KeyVaultName = ("kv" + $rgClean).Substring(0, [Math]::Min(24, ("kv" + $rgClean).Length))
        Write-InfoLog "Using auto-generated Key Vault name: $script:KeyVaultName"
    }
    
    Write-Host ""
    Write-Host "Azure Configuration:" -ForegroundColor Cyan
    Write-Host "  Subscription: $script:SubscriptionName" -ForegroundColor Gray
    Write-Host "  Subscription ID: $script:SubscriptionId" -ForegroundColor Gray
    Write-Host "  Resource Group: $script:ResourceGroup" -ForegroundColor Gray
    Write-Host "  Location: $script:Location" -ForegroundColor Gray
    Write-Host "  Cluster Name: $script:ClusterName" -ForegroundColor Gray
    Write-Host "  Namespace: $script:NamespaceName" -ForegroundColor Gray
    Write-Host "  Storage Account: $script:StorageAccountName" -ForegroundColor Gray
    Write-Host "  Schema Registry: $script:SchemaRegistryName" -ForegroundColor Gray
    Write-Host "  Key Vault: $script:KeyVaultName" -ForegroundColor Gray
    Write-Host "  Container Registry: $script:ContainerRegistryName ($script:ContainerRegistryLoginServer)" -ForegroundColor Gray
    Write-Host ""
    
    # Get current user's object ID for Key Vault access policy
    Write-Log "Getting current user's object ID..."
    $script:UserObjectId = az ad signed-in-user show --query id -o tsv 2>$null
    if ($script:UserObjectId) {
        Write-InfoLog "Current user object ID: $script:UserObjectId"
    } else {
        Write-Warning "Could not get current user's object ID. Key Vault access policy will need to be set manually."
    }
    
    Write-Success "Azure authentication configured"
}

# ============================================================================
# ARM TEMPLATE DEPLOYMENT
# ============================================================================

function Deploy-ARMTemplate {
    param(
        [Parameter(Mandatory=$true)]
        [string]$TemplateName,
        
        [Parameter(Mandatory=$true)]
        [hashtable]$Parameters,
        
        [Parameter(Mandatory=$false)]
        [string]$DeploymentName = "",
        
        [Parameter(Mandatory=$false)]
        [switch]$SubscriptionLevel
    )
    
    $templatePath = Join-Path $script:ArmTemplatesDir "$TemplateName.json"
    
    if (-not (Test-Path $templatePath)) {
        Write-ErrorLog "ARM template not found: $templatePath"
        return $null
    }
    
    if (-not $DeploymentName) {
        $DeploymentName = "$TemplateName-$(Get-Date -Format 'yyyyMMddHHmmss')"
    }
    
    # Build parameters as individual arguments (avoid JSON parsing issues)
    $paramArgs = @()
    foreach ($param in $Parameters.GetEnumerator()) {
        $paramArgs += "$($param.Key)=$($param.Value)"
    }
    
    Write-Log "Deploying ARM template: $TemplateName"
    Write-InfoLog "Parameters: $($paramArgs -join ', ')"
    
    if ($DryRun) {
        # Use what-if for validation
        if ($SubscriptionLevel) {
            Write-InfoLog "[DRY-RUN] Validating subscription-level deployment..."
            $result = & az deployment sub what-if `
                --location $script:Location `
                --template-file $templatePath `
                --parameters @paramArgs `
                --output json 2>&1
        } else {
            Write-InfoLog "[DRY-RUN] Validating resource group deployment..."
            $result = & az deployment group what-if `
                --resource-group $script:ResourceGroup `
                --template-file $templatePath `
                --parameters @paramArgs `
                --output json 2>&1
        }
        
        if ($LASTEXITCODE -eq 0) {
            Write-Success "[DRY-RUN] Template validation passed: $TemplateName"
            return @{ success = $true; dryRun = $true }
        } else {
            Write-ErrorLog "[DRY-RUN] Template validation failed: $result"
            return @{ success = $false; error = $result }
        }
    }
    
    # Actual deployment
    if ($SubscriptionLevel) {
        $result = & az deployment sub create `
            --location $script:Location `
            --name $DeploymentName `
            --template-file $templatePath `
            --parameters @paramArgs `
            --output json 2>&1
    } else {
        $result = & az deployment group create `
            --resource-group $script:ResourceGroup `
            --name $DeploymentName `
            --template-file $templatePath `
            --parameters @paramArgs `
            --output json 2>&1
    }
    
    if ($LASTEXITCODE -eq 0) {
        try {
            $resultJson = if ($result -is [array]) { $result -join "`n" } else { $result }
            $deploymentResult = $resultJson | ConvertFrom-Json
            Write-Success "ARM deployment completed: $TemplateName"
            $script:DeployedResources += "$TemplateName"
            return $deploymentResult
        } catch {
            Write-Success "ARM deployment completed: $TemplateName (output parsing skipped)"
            $script:DeployedResources += "$TemplateName"
            return @{ success = $true }
        }
    } else {
        Write-ErrorLog "ARM deployment failed: $TemplateName"
        Write-ErrorLog "Error: $result"
        Write-Host ""
        Write-Host "Stopping deployment due to ARM template failure." -ForegroundColor Red
        
        # Check for authorization error and provide specific guidance
        if ($result -match "roleAssignments/write") {
            Write-Host ""
            Write-Host "============================================================================" -ForegroundColor Yellow
            Write-Host "ROLE ASSIGNMENT PERMISSION ERROR" -ForegroundColor Yellow
            Write-Host "============================================================================" -ForegroundColor Yellow
            Write-Host ""
            Write-Host "Your account cannot create role assignments (RBAC permissions)." -ForegroundColor Yellow
            Write-Host "This is needed to grant the Schema Registry access to the Storage Account." -ForegroundColor Yellow
            Write-Host ""
            Write-Host "To fix this, run the grant_entra_id_roles.ps1 script:" -ForegroundColor Cyan
            Write-Host ""
            Write-Host "  .\grant_entra_id_roles.ps1" -ForegroundColor Green
            Write-Host ""
            Write-Host "NOTE: If you already ran grant_entra_id_roles.ps1 before, you may need to" -ForegroundColor Magenta
            Write-Host "run it AGAIN. Some resources (like Schema Registry) didn't exist yet," -ForegroundColor Magenta
            Write-Host "so the script couldn't grant their role assignments the first time." -ForegroundColor Magenta
            Write-Host ""
            Write-Host "This script grants 'Role Based Access Control Administrator' (resource group" -ForegroundColor Gray
            Write-Host "scope only) which allows you to create role assignments." -ForegroundColor Gray
            Write-Host ""
            Write-Host "After running grant_entra_id_roles.ps1, run this script again." -ForegroundColor Yellow
            Write-Host "============================================================================" -ForegroundColor Yellow
        } elseif ($result -match "AuthorizationFailed|does not have authorization") {
            Write-Host ""
            Write-Host "============================================================================" -ForegroundColor Yellow
            Write-Host "AUTHORIZATION ERROR DETECTED" -ForegroundColor Yellow
            Write-Host "============================================================================" -ForegroundColor Yellow
            Write-Host ""
            Write-Host "Your account does not have sufficient permissions to deploy ARM templates." -ForegroundColor Yellow
            Write-Host "You need 'Contributor' or 'Owner' role on the subscription." -ForegroundColor Yellow
            Write-Host ""
            Write-Host "To grant the required permissions, run:" -ForegroundColor Cyan
            Write-Host ""
            Write-Host "  .\grant_entra_id_roles.ps1" -ForegroundColor Green
            Write-Host ""
            Write-Host "Or ask your Azure admin to grant you one of these roles:" -ForegroundColor Gray
            Write-Host "  - Contributor (can deploy resources)" -ForegroundColor Gray
            Write-Host "  - Owner (can deploy resources and manage access)" -ForegroundColor Gray
            Write-Host ""
            Write-Host "After permissions are granted, run this script again." -ForegroundColor Yellow
            Write-Host "============================================================================" -ForegroundColor Yellow
        } else {
            Write-Host "Please fix the issue above and run the script again." -ForegroundColor Yellow
        }
        
        Write-ErrorLog "ARM deployment failed - cannot continue" -Fatal
    }
}

# ============================================================================
# INFRASTRUCTURE DEPLOYMENT
# ============================================================================

function Deploy-Infrastructure {
    Write-Log "Deploying Azure infrastructure via ARM templates..."
    
    # Step 1: Create Resource Group (check if exists first to minimize permission requirements)
    Write-Log "Step 1/7: Checking resource group..."
    
    $rgExists = az group exists --name $script:ResourceGroup 2>$null
    if ($rgExists -eq "true") {
        Write-Success "Resource group already exists: $script:ResourceGroup"
    } else {
        Write-Log "Resource group does not exist, creating via Azure CLI..."
        
        if ($DryRun) {
            Write-InfoLog "[DRY-RUN] Would create resource group: $script:ResourceGroup in $script:Location"
        } else {
            # Use az group create instead of ARM template - requires fewer permissions
            $rgResult = az group create `
                --name $script:ResourceGroup `
                --location $script:Location `
                --tags project=azure-iot-operations cluster=$script:ClusterName `
                --output json 2>&1
            
            if ($LASTEXITCODE -eq 0) {
                Write-Success "Resource group created: $script:ResourceGroup"
                $script:DeployedResources += "ResourceGroup:$script:ResourceGroup"
            } else {
                Write-ErrorLog "Failed to create resource group"
                Write-ErrorLog "Error: $rgResult"
                Write-Host ""
                Write-Host "You may need 'Contributor' role at the subscription level to create resource groups." -ForegroundColor Yellow
                Write-Host "Alternatively, ask your Azure admin to create the resource group for you:" -ForegroundColor Gray
                Write-Host "  az group create --name $script:ResourceGroup --location $script:Location" -ForegroundColor Cyan
                Write-Host ""
                Write-ErrorLog "Cannot continue without resource group" -Fatal
            }
        }
    }
    
    # Step 2: Create Storage Account
    Write-Log "Step 2/7: Creating storage account..."
    # Check if storage account already exists (name is globally unique across Azure)
    # First check in our resource group, then check global availability
    $existingStorage = az storage account show --name $script:StorageAccountName --resource-group $script:ResourceGroup --query "name" -o tsv 2>$null
    if ($existingStorage) {
        Write-Success "Storage account already exists in resource group: $script:StorageAccountName (reusing)"
        $storageResult = @{ success = $true }
    } else {
        # Check if the name is taken globally (by another RG/subscription)
        $nameCheck = az storage account check-name --name $script:StorageAccountName --query "nameAvailable" -o tsv 2>$null
        if ($nameCheck -eq "false") {
            # Name taken globally - check if it exists anywhere in our subscription
            $existingInSub = az storage account list --query "[?name=='$($script:StorageAccountName)'].{name:name, rg:resourceGroup}" -o json 2>$null | ConvertFrom-Json
            if ($existingInSub -and $existingInSub.Count -gt 0) {
                Write-WarnLog "Storage account '$($script:StorageAccountName)' exists in resource group '$($existingInSub[0].rg)' (different from '$($script:ResourceGroup)')"
                Write-Success "Reusing existing storage account: $script:StorageAccountName"
                $storageResult = @{ success = $true }
            } else {
                Write-WarnLog "Storage account name '$($script:StorageAccountName)' is taken globally by another Azure subscription."
                Write-Host "Please set a unique 'storage_account_name' in config/aio_config.json and retry." -ForegroundColor Yellow
                Write-ErrorLog "Cannot create storage account - name globally taken" -Fatal
            }
        } else {
            $storageResult = Deploy-ARMTemplate -TemplateName "storageAccount" -Parameters @{
                storageAccountName = $script:StorageAccountName
                location = $script:Location
            }
        }
    }
    
    # TODO (fabric-entra-id-gap): Key Vault + secret sync are required today specifically for
    # Fabric SASL auth. When Fabric supports Entra ID on custom Kafka endpoints, this step and
    # the secretsync enable below can be removed for the Fabric RTI flow. See issues/fabric_entra_id_gap.md.
    # Step 3: Create Key Vault
    Write-Log "Step 3/7: Creating Key Vault..."
    # Check if Key Vault already exists (name is globally unique across Azure)
    $existingKv = az keyvault show --name $script:KeyVaultName --resource-group $script:ResourceGroup --query "name" -o tsv 2>$null
    if ($existingKv) {
        Write-Success "Key Vault already exists in resource group: $script:KeyVaultName (reusing)"
        $kvResult = @{ success = $true }
    } else {
        # Check if the name is taken globally (including soft-deleted vaults)
        $existingKvAnywhere = az keyvault show --name $script:KeyVaultName --query "name" -o tsv 2>$null
        if ($existingKvAnywhere) {
            Write-WarnLog "Key Vault '$($script:KeyVaultName)' exists in a different resource group"
            Write-Success "Reusing existing Key Vault: $script:KeyVaultName"
            $kvResult = @{ success = $true }
        } else {
            $kvParams = @{
                keyVaultName = $script:KeyVaultName
                location = $script:Location
            }
            # Add user access policy if we have the user's object ID
            if ($script:UserObjectId) {
                $kvParams.userObjectId = $script:UserObjectId
                Write-InfoLog "Adding access policy for current user to Key Vault"
            }
            $kvResult = Deploy-ARMTemplate -TemplateName "keyVault" -Parameters $kvParams
        }
    }
    
    # Step 4: Create Device Registry Namespace
    Write-Log "Step 4/7: Creating Device Registry namespace..."
    $nsResult = Deploy-ARMTemplate -TemplateName "deviceRegistryNamespace" -Parameters @{
        namespaceName = $script:NamespaceName
        location = $script:Location
    }
    
    # Step 5: Create Schema Registry
    Write-Log "Step 5/7: Creating Schema Registry..."
    $srResult = Deploy-ARMTemplate -TemplateName "schemaRegistry" -Parameters @{
        schemaRegistryName = $script:SchemaRegistryName
        location = $script:Location
        storageAccountName = $script:StorageAccountName
    }
    
    # Step 6: Create Managed Identity for secret sync
    Write-Log "Step 6/7: Creating Managed Identity..."
    $miName = "$($script:ClusterName)-secretsync-mi"
    $miResult = Deploy-ARMTemplate -TemplateName "managedIdentity" -Parameters @{
        managedIdentityName = $miName
        location = $script:Location
    }
    
    # Configure Key Vault RBAC role assignments for managed identities
    # Using RBAC instead of access policies for better security and management
    Write-Log "Configuring Key Vault RBAC role assignments for AIO dataflows..."
    
    # Key Vault Secrets User role ID (built-in role for reading secrets)
    $kvSecretsUserRoleId = "4633458b-17de-408a-b874-0445c86b69e6"
    $kvResourceId = "/subscriptions/$script:SubscriptionId/resourceGroups/$script:ResourceGroup/providers/Microsoft.KeyVault/vaults/$script:KeyVaultName"
    
    if (-not $DryRun) {
        # Get the managed identity's principal ID
        $miPrincipalId = az identity show --name $miName --resource-group $script:ResourceGroup --query "principalId" -o tsv 2>$null
        
        if ($miPrincipalId) {
            Write-InfoLog "Assigning Key Vault Secrets User role to $miName..."
            az role assignment create `
                --role $kvSecretsUserRoleId `
                --assignee-object-id $miPrincipalId `
                --assignee-principal-type ServicePrincipal `
                --scope $kvResourceId `
                --output none 2>$null
            
            if ($LASTEXITCODE -eq 0) {
                Write-Success "Granted Key Vault Secrets User role to $miName"
            } else {
                Write-WarnLog "Failed to assign Key Vault role for $miName (may already exist)"
            }
        } else {
            Write-WarnLog "Could not get principal ID for $miName"
        }
        
        # Also check for any other managed identities in the resource group and grant them access
        $allManagedIdentities = az identity list --resource-group $script:ResourceGroup --query "[].{name:name, principalId:principalId}" 2>$null | ConvertFrom-Json
        
        if ($allManagedIdentities) {
            foreach ($identity in $allManagedIdentities) {
                # Skip the one we just configured
                if ($identity.name -eq $miName) { continue }
                
                # Only configure identities that look like they're for secret sync or AIO
                if ($identity.name -match "secretsync|aio|iot") {
                    Write-InfoLog "Assigning Key Vault Secrets User role to $($identity.name)..."
                    az role assignment create `
                        --role $kvSecretsUserRoleId `
                        --assignee-object-id $identity.principalId `
                        --assignee-principal-type ServicePrincipal `
                        --scope $kvResourceId `
                        --output none 2>$null
                    
                    if ($LASTEXITCODE -eq 0) {
                        Write-Success "Granted Key Vault Secrets User role to $($identity.name)"
                    }
                }
            }
        }
    } else {
        Write-InfoLog "[DRY RUN] Would configure Key Vault RBAC role assignments for managed identities"
    }
    
    # Step 7: Create Container Registry
    Write-Log "Step 7/7: Creating Container Registry..."
    $existingAcr = az acr show --name $script:ContainerRegistryName --resource-group $script:ResourceGroup --query "name" -o tsv 2>$null
    if ($existingAcr) {
        Write-Success "Container registry already exists: $script:ContainerRegistryName (reusing)"
        $script:ContainerRegistryLoginServer = az acr show --name $script:ContainerRegistryName --query "loginServer" -o tsv 2>$null
    } else {
        # Check global name availability (ACR names are globally unique)
        $acrNameCheck = az acr check-name --name $script:ContainerRegistryName --query "nameAvailable" -o tsv 2>$null
        if ($acrNameCheck -eq "false") {
            Write-WarnLog "ACR name '$($script:ContainerRegistryName)' is already taken globally."
            Write-WarnLog "Set a unique 'container_registry' name in config/aio_config.json and retry."
        } else {
            $acrResult = Deploy-ARMTemplate -TemplateName "containerRegistry" -Parameters @{
                registryName = $script:ContainerRegistryName
                location     = $script:Location
            }
            if ($acrResult.success) {
                $script:ContainerRegistryLoginServer = az acr show --name $script:ContainerRegistryName --query "loginServer" -o tsv 2>$null
                Write-Success "Container registry created: $script:ContainerRegistryLoginServer"
                $script:DeployedResources += "ContainerRegistry:$script:ContainerRegistryName"

                # Update aio_config.json with the login server so Deploy-EdgeModules.ps1 picks it up
                $configPath = Join-Path $script:ConfigDir "aio_config.json"
                if (Test-Path $configPath) {
                    try {
                        $cfg = Get-Content $configPath -Raw | ConvertFrom-Json
                        $cfg.azure.container_registry = $script:ContainerRegistryLoginServer
                        $cfg | ConvertTo-Json -Depth 10 | Set-Content $configPath -Encoding UTF8
                        Write-InfoLog "Updated aio_config.json: container_registry = $script:ContainerRegistryLoginServer"
                    } catch {
                        Write-WarnLog "Could not auto-update aio_config.json with registry login server: $_"
                    }
                }
            }
        }
    }

    # Role assignments are handled by grant_entra_id_roles.ps1
    # This separation allows different people (admin vs developer) to run different scripts
    Write-Host ""
    Write-Host "============================================================================" -ForegroundColor Cyan
    Write-Host "ROLE ASSIGNMENTS REMINDER" -ForegroundColor Cyan
    Write-Host "============================================================================" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "Infrastructure resources have been created. Role assignments (RBAC) are" -ForegroundColor Yellow
    Write-Host "handled separately by grant_entra_id_roles.ps1 to allow separation of duties." -ForegroundColor Yellow
    Write-Host ""
    Write-Host "If this is your first run, or if new resources were created, run:" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "  .\grant_entra_id_roles.ps1" -ForegroundColor Green
    Write-Host ""
    Write-Host "This grants permissions like:" -ForegroundColor Gray
    Write-Host "  - Schema Registry -> Storage Blob Data Contributor" -ForegroundColor Gray
    Write-Host "  - Managed Identity -> Key Vault Secrets User" -ForegroundColor Gray
    Write-Host "  - AIO Instance -> Event Hubs permissions for Fabric" -ForegroundColor Gray
    Write-Host "  - AIO Instance -> AcrPull on Container Registry (via grant_entra_id_roles.ps1)" -ForegroundColor Gray
    Write-Host ""
    Write-Host "============================================================================" -ForegroundColor Cyan
    Write-Host ""
    
    Write-Success "Infrastructure deployment completed"
}

# ============================================================================
# ARC ENABLEMENT (Requires Azure CLI - no ARM template available)
# ============================================================================
# ============================================================================
# IOT OPERATIONS DEPLOYMENT (Requires Azure CLI)
# ============================================================================
# NOTE: Arc enablement is handled by arc_enable.ps1 on the edge device
# This script assumes the cluster is already Arc-enabled

function Register-AcrRegistryEndpoint {
    param(
        [Parameter(Mandatory=$true)]
        [string]$InstanceName
    )

    if (-not $script:ContainerRegistryLoginServer) {
        Write-WarnLog "No container registry configured - skipping registry endpoint registration."
        return
    }

    Write-Log "Registering ACR as AIO registry endpoint: $script:ContainerRegistryLoginServer"

    if ($DryRun) {
        Write-InfoLog "[DRY-RUN] Would register registry endpoint for $script:ContainerRegistryLoginServer"
        return
    }

    # Derive a consistent endpoint name from the registry name
    $endpointName = "$($script:ContainerRegistryName)-endpoint"

    # --- Step 1: Ensure AcrPull is granted to the AIO managed identity (safety net) ---
    # grant_entra_id_roles.ps1 handles this in the normal flow; this is a fallback
    # for cases where it hasn't been run yet or ran before AIO was deployed.
    Write-InfoLog "Ensuring AcrPull role is assigned to AIO instance managed identity..."
    $aioIdentity = az iot ops show `
        --name $InstanceName `
        --resource-group $script:ResourceGroup `
        --query "identity.principalId" -o tsv 2>$null

    $acrResourceId = az acr show `
        --name $script:ContainerRegistryName `
        --resource-group $script:ResourceGroup `
        --query "id" -o tsv 2>$null

    if ($aioIdentity -and $acrResourceId) {
        az role assignment create `
            --role "AcrPull" `
            --assignee-object-id $aioIdentity `
            --assignee-principal-type ServicePrincipal `
            --scope $acrResourceId `
            --output none 2>$null
        # Non-zero exit is expected when the assignment already exists - not fatal
        Write-InfoLog "AcrPull role assignment applied (idempotent)."
    } else {
        Write-WarnLog "Could not resolve AIO identity or ACR resource ID - AcrPull may need to be set manually via grant_entra_id_roles.ps1."
    }

    # --- Step 2: Check if the registry endpoint is already registered ---
    $existingEndpoint = az iot ops registry list `
        --instance $InstanceName `
        --resource-group $script:ResourceGroup `
        --query "[?properties.server=='$script:ContainerRegistryLoginServer'].name" `
        -o tsv 2>$null

    if ($existingEndpoint) {
        Write-Success "Registry endpoint already registered for $script:ContainerRegistryLoginServer ($existingEndpoint) - skipping."
        return
    }

    # --- Step 3: Create the registry endpoint ---
    Write-Log "Creating registry endpoint '$endpointName'..."
    az iot ops registry create `
        --name $endpointName `
        --host $script:ContainerRegistryLoginServer `
        --instance $InstanceName `
        --resource-group $script:ResourceGroup `
        --output none 2>&1

    if ($LASTEXITCODE -eq 0) {
        Write-Success "Registry endpoint created: $endpointName -> $script:ContainerRegistryLoginServer"
        $script:DeployedResources += "RegistryEndpoint:$endpointName"
    } else {
        Write-WarnLog "Registry endpoint creation returned non-zero. It may already exist or the AIO instance is not yet ready."
        Write-WarnLog "You can register it manually with:"
        Write-WarnLog "  az iot ops registry create -n $endpointName --host $script:ContainerRegistryLoginServer -i $InstanceName -g $script:ResourceGroup"
    }
}

function Deploy-IoTOperations {
    if ($SkipIoTOps) {
        Write-InfoLog "Skipping IoT Operations deployment (-SkipIoTOps flag)"
        return
    }
    
    Write-Log "Deploying Azure IoT Operations..."
    Write-InfoLog "Note: IoT Operations deployment requires Azure CLI (no ARM template available)"
    
    # Enable UTF-8 encoding
    [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
    $env:PYTHONIOENCODING = "utf-8"
    $env:PYTHONUTF8 = "1"
    chcp 65001 2>&1 | Out-Null
    
    $instanceName = "$script:ClusterName-aio"
    
    if ($DryRun) {
        Write-InfoLog "[DRY-RUN] Would deploy Azure IoT Operations instance: $instanceName"
        Write-InfoLog "[DRY-RUN] az iot ops init --cluster $script:ClusterName --resource-group $script:ResourceGroup"
        Write-InfoLog "[DRY-RUN] az iot ops create --cluster $script:ClusterName --resource-group $script:ResourceGroup --name $instanceName"
        return
    }
    
    # Check if already deployed
    $existingInstance = az iot ops show --name $instanceName --resource-group $script:ResourceGroup 2>&1
    
    $aioAlreadyExists = $LASTEXITCODE -eq 0
    
    if ($aioAlreadyExists) {
        Write-Success "Azure IoT Operations instance $instanceName already exists"
        Write-InfoLog "Verifying Key Vault access policies are configured..."
    } else {
        # Check Arc cluster connectivity
        Write-Log "Checking Arc cluster connectivity..."
        $clusterResult = az connectedk8s show `
        --name $script:ClusterName `
        --resource-group $script:ResourceGroup `
        --output json 2>&1
    
    if ($LASTEXITCODE -ne 0) {
        Write-Host ""
        Write-Host "============================================================================" -ForegroundColor Red
        Write-Host "ARC CLUSTER NOT FOUND" -ForegroundColor Red
        Write-Host "============================================================================" -ForegroundColor Red
        Write-Host ""
        Write-Host "The Arc-enabled cluster '$script:ClusterName' was not found in resource group '$script:ResourceGroup'." -ForegroundColor Yellow
        Write-Host ""
        Write-Host "This means Arc enablement has not been completed yet." -ForegroundColor Yellow
        Write-Host ""
        Write-Host "To fix this:" -ForegroundColor Cyan
        Write-Host ""
        Write-Host "  1. On your EDGE DEVICE (Linux), run:" -ForegroundColor Green
        Write-Host "     pwsh ./arc_enable.ps1" -ForegroundColor White
        Write-Host ""
        Write-Host "  2. Wait for it to complete, then run this script again." -ForegroundColor Green
        Write-Host ""
        Write-Host "If you already ran arc_enable.ps1, check:" -ForegroundColor Cyan
        Write-Host "  - Did it complete successfully?" -ForegroundColor Gray
        Write-Host "  - Is the cluster name correct? Expected: $script:ClusterName" -ForegroundColor Gray
        Write-Host "  - Is the resource group correct? Expected: $script:ResourceGroup" -ForegroundColor Gray
        Write-Host ""
        Write-Host "To verify Arc status from the edge device:" -ForegroundColor Cyan
        Write-Host "  kubectl get pods -n azure-arc" -ForegroundColor White
        Write-Host ""
        Write-Host "============================================================================" -ForegroundColor Red
        Write-ErrorLog "Arc cluster not found - cannot deploy IoT Operations" -Fatal
    }
    
    $clusterJson = if ($clusterResult -is [array]) { $clusterResult -join "`n" } else { $clusterResult }
    $clusterData = $clusterJson | ConvertFrom-Json
    $clusterStatus = $clusterData.connectivityStatus
    
    if ($clusterStatus -ne "Connected") {
        Write-Host ""
        Write-Host "============================================================================" -ForegroundColor Red
        Write-Host "ARC CLUSTER NOT CONNECTED" -ForegroundColor Red
        Write-Host "============================================================================" -ForegroundColor Red
        Write-Host ""
        Write-Host "The Arc cluster exists but is not connected." -ForegroundColor Yellow
        Write-Host "  Cluster: $script:ClusterName" -ForegroundColor Gray
        Write-Host "  Status:  $clusterStatus" -ForegroundColor Gray
        Write-Host ""
        Write-Host "The cluster must be 'Connected' before IoT Operations can be deployed." -ForegroundColor Yellow
        Write-Host ""
        Write-Host "Troubleshooting steps (run on the EDGE DEVICE):" -ForegroundColor Cyan
        Write-Host ""
        Write-Host "  1. Check if K3s is running:" -ForegroundColor Green
        Write-Host "     sudo systemctl status k3s" -ForegroundColor White
        Write-Host ""
        Write-Host "  2. Check Arc agent pods:" -ForegroundColor Green
        Write-Host "     kubectl get pods -n azure-arc" -ForegroundColor White
        Write-Host ""
        Write-Host "  3. Check Arc agent logs:" -ForegroundColor Green
        Write-Host "     kubectl logs -n azure-arc -l app.kubernetes.io/component=connect-agent --tail=50" -ForegroundColor White
        Write-Host ""
        Write-Host "  4. If pods are not running, restart K3s:" -ForegroundColor Green
        Write-Host "     sudo systemctl restart k3s" -ForegroundColor White
        Write-Host ""
        Write-Host "  5. Check network connectivity from edge device:" -ForegroundColor Green
        Write-Host "     curl -s https://management.azure.com" -ForegroundColor White
        Write-Host ""
        Write-Host "Common issues:" -ForegroundColor Cyan
        Write-Host "  - Network/firewall blocking outbound connections to Azure" -ForegroundColor Gray
        Write-Host "  - DNS resolution issues on the edge device" -ForegroundColor Gray
        Write-Host "  - K3s service not running" -ForegroundColor Gray
        Write-Host "  - Arc agents crashed (check pod status)" -ForegroundColor Gray
        Write-Host ""
        Write-Host "After fixing the issue, check status with:" -ForegroundColor Cyan
        Write-Host "  az connectedk8s show --name $script:ClusterName --resource-group $script:ResourceGroup --query connectivityStatus" -ForegroundColor White
        Write-Host ""
        Write-Host "============================================================================" -ForegroundColor Red
        Write-ErrorLog "Arc cluster not connected (status: $clusterStatus) - cannot deploy IoT Operations" -Fatal
    }
    
    Write-Success "Arc cluster status: Connected"
    
    # Check if custom-locations feature is enabled (required for IoT Operations)
    Write-Log "Checking custom-locations feature on Arc cluster..."
    
    # Get the Custom Locations Resource Provider object ID for this tenant
    # The Application ID bc313c14-388c-4e7d-a58e-70017303ee3b is fixed globally for the Custom Locations RP
    $customLocationsAppId = "bc313c14-388c-4e7d-a58e-70017303ee3b"
    $customLocationsOid = az ad sp show --id $customLocationsAppId --query id -o tsv 2>$null
    
    if ([string]::IsNullOrEmpty($customLocationsOid)) {
        Write-WarnLog "Could not retrieve Custom Locations Resource Provider object ID"
    } else {
        Write-InfoLog "Custom Locations RP Object ID: $customLocationsOid"
    }
    
    # Check cluster properties - custom-locations is considered enabled if:
    # 1. Cluster is Connected
    # 2. PrivateLinkState is Disabled (custom-locations incompatible with Private Link)
    # Note: The 'features' property in az connectedk8s show is NOT populated when
    # custom-locations is enabled via -CustomLocationsOid during New-AzConnectedKubernetes.
    # The feature is still enabled, it just doesn't show in that property.
    $clusterInfoRaw = az connectedk8s show `
        --name $script:ClusterName `
        --resource-group $script:ResourceGroup `
        -o json 2>$null
    $clusterInfoJson = if ($clusterInfoRaw -is [array]) { $clusterInfoRaw -join "`n" } else { $clusterInfoRaw }
    $clusterInfo = $clusterInfoJson | ConvertFrom-Json
    
    $customLocationsEnabled = $false
    $blockingReason = ""
    
    if ($clusterInfo) {
        # Check for blocking conditions
        if ($clusterInfo.privateLinkState -eq "Enabled") {
            $blockingReason = "Private Link is enabled (incompatible with custom-locations)"
        } elseif ($clusterInfo.connectivityStatus -ne "Connected") {
            $blockingReason = "Cluster is not connected (status: $($clusterInfo.connectivityStatus))"
        } else {
            # Cluster is connected with Private Link disabled - custom-locations should work
            # The feature was enabled via -CustomLocationsOid during arc_enable.ps1
            $customLocationsEnabled = $true
            
            # Also check the features array if it exists (belt and suspenders)
            if ($clusterInfo.features) {
                foreach ($feature in $clusterInfo.features) {
                    if ($feature.name -eq "custom-locations" -and $feature.state -eq "Installed") {
                        Write-InfoLog "custom-locations feature explicitly confirmed in cluster properties"
                        break
                    }
                }
            }
        }
    } else {
        $blockingReason = "Could not retrieve cluster information"
    }
    
    if ($customLocationsEnabled) {
        Write-Success "Custom-locations feature is enabled (cluster connected, Private Link disabled)"
        Write-WarnLog "NOTE: ARM shows custom-locations is configured, but the Helm chart must also be updated."
        Write-InfoLog "If 'az iot ops create' fails with 'resource provider does not have required permissions',"
        Write-InfoLog "you need to run this on your EDGE device:"
        Write-Host ""
        Write-Host "  az connectedk8s enable-features \" -ForegroundColor Cyan
        Write-Host "    --name $script:ClusterName \" -ForegroundColor Cyan
        Write-Host "    --resource-group $script:ResourceGroup \" -ForegroundColor Cyan
        Write-Host "    --features cluster-connect custom-locations \" -ForegroundColor Cyan
        Write-Host "    --custom-locations-oid $customLocationsOid" -ForegroundColor Cyan
        Write-Host ""
        Write-InfoLog "Or re-run arc_enable.ps1 on the edge device (it will do this for you)."
        Write-Host ""
    } else {
        Write-Host ""
        Write-Host "============================================================================" -ForegroundColor Red
        Write-Host "CUSTOM-LOCATIONS CANNOT BE VERIFIED" -ForegroundColor Red
        Write-Host "============================================================================" -ForegroundColor Red
        Write-Host ""
        Write-Host "Reason: $blockingReason" -ForegroundColor Yellow
        Write-Host ""
        Write-Host "The custom-locations feature is required for Azure IoT Operations." -ForegroundColor Yellow
        Write-Host ""
        Write-Host "If you ran arc_enable.ps1 on the edge device and it completed successfully," -ForegroundColor Cyan
        Write-Host "you also need to run the helm upgrade step on the edge device." -ForegroundColor Cyan
        Write-Host ""
        Write-Host "IMPORTANT: The Az.ConnectedKubernetes PowerShell module has a gap where" -ForegroundColor Yellow
        Write-Host "-CustomLocationsOid only registers with ARM but doesn't update Helm." -ForegroundColor Yellow
        Write-Host ""
        Write-Host "To fix, on your EDGE DEVICE:" -ForegroundColor Cyan
        Write-Host ""
        Write-Host "  # Check if custom-locations is enabled in Helm:" -ForegroundColor Gray
        Write-Host "  helm get values azure-arc --namespace azure-arc-release -o json | jq '.systemDefaultValues.customLocations'" -ForegroundColor White
        Write-Host ""
        Write-Host "  # If it shows 'null', run:" -ForegroundColor Gray
        Write-Host "  az connectedk8s enable-features \" -ForegroundColor White
        Write-Host "    --name $script:ClusterName \" -ForegroundColor White
        Write-Host "    --resource-group $script:ResourceGroup \" -ForegroundColor White
        Write-Host "    --features cluster-connect custom-locations \" -ForegroundColor White
        Write-Host "    --custom-locations-oid $customLocationsOid" -ForegroundColor White
        Write-Host ""
        Write-Host "  # Or re-run arc_enable.ps1 (includes this step):" -ForegroundColor Gray
        Write-Host "  cd ~/learn-iot/arc_build_linux && git pull" -ForegroundColor White
        Write-Host "  pwsh ./arc_enable.ps1" -ForegroundColor White
        Write-Host ""
        Write-Host "Then re-run this script." -ForegroundColor Cyan
        Write-Host ""
        Write-Host "============================================================================" -ForegroundColor Red
        Write-ErrorLog "Custom-locations feature not enabled - cannot deploy IoT Operations. Reason: $blockingReason" -Fatal
    }
    
    # Check if IoT Operations already exists on this cluster
    $existingInstance = az iot ops show --name $instanceName --resource-group $script:ResourceGroup --query "provisioningState" -o tsv 2>$null
    if ($existingInstance) {
        Write-Success "IoT Operations instance already exists: $instanceName (State: $existingInstance) - skipping create"
        
        # Try upgrade instead to pick up any config changes
        Write-Log "Running IoT Operations upgrade to apply any pending updates..."
        az iot ops upgrade --name $instanceName --resource-group $script:ResourceGroup -y 2>&1
        if ($LASTEXITCODE -eq 0) {
            Write-Success "IoT Operations upgrade completed"
        } else {
            Write-WarnLog "IoT Operations upgrade returned non-zero (may already be up to date)"
        }
    } else {
        # Initialize cluster
        Write-Log "Initializing cluster for Azure IoT Operations..."
        az iot ops init --cluster $script:ClusterName --resource-group $script:ResourceGroup
        
        # Get schema registry ID
        $schemaRegistryId = az resource show `
            --resource-group $script:ResourceGroup `
            --resource-type "Microsoft.DeviceRegistry/schemaRegistries" `
            --name $script:SchemaRegistryName `
            --query "id" -o tsv 2>$null
        
        # Get namespace ID
        $namespaceId = "/subscriptions/$script:SubscriptionId/resourceGroups/$script:ResourceGroup/providers/Microsoft.DeviceRegistry/namespaces/$script:NamespaceName"
        
        Write-Log "Deploying Azure IoT Operations instance..."
        Write-InfoLog "This may take several minutes..."
        
        # Build az iot ops create argument list; append DemoMode broker flags if requested
        $createArgs = @(
            "iot", "ops", "create",
            "--cluster", $script:ClusterName,
            "--resource-group", $script:ResourceGroup,
            "--name", $instanceName,
            "--sr-resource-id", $schemaRegistryId,
            "--ns-resource-id", $namespaceId,
            "--no-progress"
        )
        if ($DemoMode) {
            Write-InfoLog "[DEMO] Applying low-resource broker sizing (~303 MiB RAM vs ~15.8 GB default)"
            Write-InfoLog "[DEMO] Ref: https://learn.microsoft.com/azure/iot-operations/manage-mqtt-broker/howto-configure-availability-scale"
            $createArgs += "--broker-frontend-replicas", "1",
                           "--broker-frontend-workers",  "1",
                           "--broker-backend-part",      "1",
                           "--broker-backend-rf",        "2",
                           "--broker-backend-workers",   "1",
                           "--broker-mem-profile",       "Tiny"
        }
        az @createArgs 2>&1
        
        if ($LASTEXITCODE -ne 0) {
            Write-ErrorLog "Azure IoT Operations deployment failed"
            return
        }
        
        Write-Success "Azure IoT Operations deployed: $instanceName"
    }
    $script:DeployedResources += "IoTOperationsInstance:$instanceName"

    # Enable secret sync
    Write-Log "Enabling secret sync..."
    $miName = "$($script:ClusterName)-secretsync-mi"
    $miResourceId = az identity show `
        --name $miName `
        --resource-group $script:ResourceGroup `
        --query "id" -o tsv 2>$null
    
    if ($miResourceId) {
        # IMPORTANT: Key Vault RBAC role must be assigned BEFORE enabling secretsync
        Write-InfoLog "Assigning Key Vault Secrets User role to secret sync managed identity (required before secretsync)..."
        $miPrincipalId = az identity show --name $miName --resource-group $script:ResourceGroup --query "principalId" -o tsv 2>$null
        
        # Key Vault Secrets User role ID
        $kvSecretsUserRoleId = "4633458b-17de-408a-b874-0445c86b69e6"
        $kvResourceId = "/subscriptions/$script:SubscriptionId/resourceGroups/$script:ResourceGroup/providers/Microsoft.KeyVault/vaults/$script:KeyVaultName"
        
        if ($miPrincipalId) {
            az role assignment create `
                --role $kvSecretsUserRoleId `
                --assignee-object-id $miPrincipalId `
                --assignee-principal-type ServicePrincipal `
                --scope $kvResourceId `
                --output none 2>$null
            
            if ($LASTEXITCODE -eq 0) {
                Write-Success "Granted Key Vault Secrets User role to $miName"
            } else {
                Write-WarnLog "Failed to assign Key Vault role for $miName - secretsync may fail (role may already exist)"
            }
        }
        
        # TODO (fabric-entra-id-gap): secretsync enable is required today for Fabric SASL auth.
        # See issues/fabric_entra_id_gap.md.
        # Now enable secretsync
        az iot ops secretsync enable `
            --name $instanceName `
            --resource-group $script:ResourceGroup `
            --mi-user-assigned $miResourceId `
            --kv-resource-id $kvResourceId 2>$null
        
        Write-Success "Secret sync enabled"
        }
    }  # End of else block (AIO deployment)

    # Register ACR as a named registry endpoint inside AIO
    # (runs whether AIO was just created or already existed)
    Register-AcrRegistryEndpoint -InstanceName $instanceName

    # Configure Key Vault RBAC role assignments for Arc cluster and AIO instance
    # This runs whether AIO was just deployed or already existed
    Write-Log "Configuring Key Vault RBAC role assignments for AIO identities..."
    
    # Key Vault Secrets User role ID
    $kvSecretsUserRoleId = "4633458b-17de-408a-b874-0445c86b69e6"
    $kvResourceId = "/subscriptions/$script:SubscriptionId/resourceGroups/$script:ResourceGroup/providers/Microsoft.KeyVault/vaults/$script:KeyVaultName"
    
    # Grant Arc cluster identity access to Key Vault
    $arcIdentity = az connectedk8s show --name $script:ClusterName --resource-group $script:ResourceGroup --query "identity.principalId" -o tsv 2>$null
    if ($arcIdentity) {
        Write-InfoLog "Assigning Key Vault Secrets User role to Arc cluster identity..."
        az role assignment create `
            --role $kvSecretsUserRoleId `
            --assignee-object-id $arcIdentity `
            --assignee-principal-type ServicePrincipal `
            --scope $kvResourceId `
            --output none 2>$null
        
        if ($LASTEXITCODE -eq 0) {
            Write-Success "Granted Key Vault Secrets User role to Arc cluster identity"
        } else {
            Write-WarnLog "Failed to assign Key Vault role for Arc cluster identity (may already exist)"
        }
    }
    
    # Grant AIO instance identity access to Key Vault
    $aioIdentity = az iot ops show --name $instanceName --resource-group $script:ResourceGroup --query "identity.principalId" -o tsv 2>$null
    if ($aioIdentity) {
        Write-InfoLog "Assigning Key Vault Secrets User role to AIO instance identity..."
        az role assignment create `
            --role $kvSecretsUserRoleId `
            --assignee-object-id $aioIdentity `
            --assignee-principal-type ServicePrincipal `
            --scope $kvResourceId `
            --output none 2>$null
        
        if ($LASTEXITCODE -eq 0) {
            Write-Success "Granted Key Vault Secrets User role to AIO instance identity"
        } else {
            Write-WarnLog "Failed to assign Key Vault role for AIO instance identity (may already exist)"
        }
    }
}

# ============================================================================
# VERIFICATION
# ============================================================================

function Test-Deployment {
    if ($SkipVerification) {
        Write-InfoLog "Skipping verification (-SkipVerification flag)"
        return
    }
    
    if ($DryRun) {
        Write-InfoLog "[DRY-RUN] Skipping verification in dry-run mode"
        return
    }
    
    Write-Log "Verifying deployment..."
    
    # Verify resource group
    $rgExists = az group exists --name $script:ResourceGroup 2>$null
    if ($rgExists -eq "true") {
        Write-Success "Resource group verified: $script:ResourceGroup"
    } else {
        Write-WarnLog "Resource group not found: $script:ResourceGroup"
    }
    
    # Verify storage account
    $storage = az storage account show --name $script:StorageAccountName --resource-group $script:ResourceGroup 2>$null
    if ($storage) {
        Write-Success "Storage account verified: $script:StorageAccountName"
    } else {
        Write-WarnLog "Storage account not found: $script:StorageAccountName"
    }
    
    # Verify Key Vault
    $kv = az keyvault show --name $script:KeyVaultName --resource-group $script:ResourceGroup 2>$null
    if ($kv) {
        Write-Success "Key Vault verified: $script:KeyVaultName"
        
        # Check Key Vault configuration for AIO dataflows
        $kvJson = if ($kv -is [array]) { $kv -join "`n" } else { $kv }
        $kvData = $kvJson | ConvertFrom-Json
        $kvIssues = @()
        
        # Key Vault Secrets User role ID
        $kvSecretsUserRoleId = "4633458b-17de-408a-b874-0445c86b69e6"
        $kvResourceId = "/subscriptions/$script:SubscriptionId/resourceGroups/$script:ResourceGroup/providers/Microsoft.KeyVault/vaults/$script:KeyVaultName"
        
        # Check RBAC vs Access Policies
        if ($kvData.properties.enableRbacAuthorization -eq $true) {
            Write-InfoLog "Key Vault is using RBAC authorization"
            
            # Verify role assignments for AIO identities
            Write-InfoLog "Checking Key Vault RBAC role assignments..."
            
            # Get Arc cluster identity
            $arcIdentity = az connectedk8s show --name $script:ClusterName --resource-group $script:ResourceGroup --query "identity.principalId" -o tsv 2>$null
            if ($arcIdentity) {
                $arcRoleAssignment = az role assignment list --scope $kvResourceId --assignee $arcIdentity --query "[?roleDefinitionId contains '$kvSecretsUserRoleId']" 2>$null | ConvertFrom-Json
                if ($arcRoleAssignment -and $arcRoleAssignment.Count -gt 0) {
                    Write-Success "  Arc cluster identity has Key Vault Secrets User role"
                } else {
                    $kvIssues += "Arc cluster identity missing Key Vault Secrets User role"
                }
            }
            
            # Get AIO instance identity
            $instanceName = "$($script:ClusterName)-aio"
            $aioIdentity = az iot ops show --name $instanceName --resource-group $script:ResourceGroup --query "identity.principalId" -o tsv 2>$null
            if ($aioIdentity) {
                $aioRoleAssignment = az role assignment list --scope $kvResourceId --assignee $aioIdentity --query "[?roleDefinitionId contains '$kvSecretsUserRoleId']" 2>$null | ConvertFrom-Json
                if ($aioRoleAssignment -and $aioRoleAssignment.Count -gt 0) {
                    Write-Success "  AIO instance identity has Key Vault Secrets User role"
                } else {
                    $kvIssues += "AIO instance identity missing Key Vault Secrets User role"
                }
            }
            
            # Check for secretsync managed identity
            $miName = "$($script:ClusterName)-secretsync-mi"
            $secretSyncMi = az identity show --name $miName --resource-group $script:ResourceGroup --query "principalId" -o tsv 2>$null
            if ($secretSyncMi) {
                $miRoleAssignment = az role assignment list --scope $kvResourceId --assignee $secretSyncMi --query "[?roleDefinitionId contains '$kvSecretsUserRoleId']" 2>$null | ConvertFrom-Json
                if ($miRoleAssignment -and $miRoleAssignment.Count -gt 0) {
                    Write-Success "  Secret sync managed identity has Key Vault Secrets User role"
                } else {
                    $kvIssues += "Secret sync managed identity ($miName) missing Key Vault Secrets User role"
                }
            }
        } else {
            Write-WarnLog "Key Vault is using Access Policies instead of RBAC"
            $kvIssues += "Key Vault should use RBAC authorization for better security"
        }
        
        # Check soft delete (required for production)
        if ($kvData.properties.enableSoftDelete -eq $true) {
            Write-Success "  Soft delete is enabled"
        } else {
            $kvIssues += "Soft delete is not enabled (recommended for production)"
        }
        
        # Check template deployment enabled (needed for ARM deployments)
        if ($kvData.properties.enabledForTemplateDeployment -eq $true) {
            Write-Success "  Template deployment is enabled"
        } else {
            $kvIssues += "Template deployment is not enabled"
        }
        
        # Report issues
        if ($kvIssues.Count -gt 0) {
            Write-Host ""
            Write-WarnLog "Key Vault configuration issues found for AIO dataflows:"
            foreach ($issue in $kvIssues) {
                Write-WarnLog "  - $issue"
            }
            Write-Host ""
            Write-InfoLog "Run grant_entra_id_roles.ps1 to fix access policy issues"
        } else {
            Write-Success "Key Vault is properly configured for AIO dataflows"
        }
    } else {
        Write-WarnLog "Key Vault not found: $script:KeyVaultName"
    }
    
    # Verify Arc cluster
    $arc = az connectedk8s show --name $script:ClusterName --resource-group $script:ResourceGroup 2>$null
    if ($arc) {
        $arcJson = if ($arc -is [array]) { $arc -join "`n" } else { $arc }
        $arcData = $arcJson | ConvertFrom-Json
        Write-Success "Arc cluster verified: $script:ClusterName (Status: $($arcData.connectivityStatus))"
    } else {
        Write-WarnLog "Arc cluster not found: $script:ClusterName"
    }
    
    # Verify IoT Operations
    $instanceName = "$script:ClusterName-aio"
    $iotOps = az iot ops show --name $instanceName --resource-group $script:ResourceGroup 2>$null
    if ($iotOps) {
        $iotOpsJson = if ($iotOps -is [array]) { $iotOps -join "`n" } else { $iotOps }
        $iotOpsData = $iotOpsJson | ConvertFrom-Json
        Write-Success "IoT Operations verified: $instanceName (State: $($iotOpsData.provisioningState))"
    } else {
        Write-WarnLog "IoT Operations not found: $instanceName"
    }
    
    # Verify required extensions for asset sync
    # NOTE: In AIO v1.2+, deviceregistry is bundled into microsoft.iotoperations extension
    # The separate microsoft.deviceregistry.assets extension is no longer required
    Write-Log "Verifying required Kubernetes extensions..."
    $extensions = az k8s-extension list --cluster-name $script:ClusterName --resource-group $script:ResourceGroup --cluster-type connectedClusters -o json 2>$null
    
    if ($extensions) {
        # Join array of strings into single string for PS 5.1 ConvertFrom-Json compatibility
        $extJson = if ($extensions -is [array]) { $extensions -join "`n" } else { $extensions }
        $extData = $extJson | ConvertFrom-Json
        
        # Only microsoft.iotoperations is required - deviceregistry is now bundled in
        $requiredExtensions = @{
            "microsoft.iotoperations" = $false
        }
        
        $optionalExtensions = @{
            "microsoft.kubernetesworkloadidfederation" = $false
            "microsoft.deviceregistry.assets" = $false  # Legacy - now bundled in iotoperations
        }
        
        # Track failed extensions
        $failedExtensions = @()
        
        foreach ($ext in $extData) {
            $extType = $ext.extensionType.ToLower()
            $extState = $ext.provisioningState
            
            if ($requiredExtensions.ContainsKey($extType)) {
                $requiredExtensions[$extType] = $true
                if ($extState -eq "Succeeded") {
                    Write-Success "  Extension: $($ext.name) ($extType) - $extState"
                } elseif ($extState -eq "Creating" -or $extState -eq "Updating") {
                    Write-WarnLog "  Extension: $($ext.name) ($extType) - $extState (still in progress)"
                } else {
                    Write-ErrorLog "  Extension: $($ext.name) ($extType) - $extState"
                    $failedExtensions += @{ Name = $ext.name; Type = $extType; State = $extState }
                }
            } elseif ($optionalExtensions.ContainsKey($extType)) {
                $optionalExtensions[$extType] = $true
                if ($extState -eq "Failed") {
                    Write-WarnLog "  Extension: $($ext.name) ($extType) - $extState (optional, but failed)"
                    $failedExtensions += @{ Name = $ext.name; Type = $extType; State = $extState }
                } else {
                    Write-InfoLog "  Extension: $($ext.name) ($extType) - $extState"
                }
            } else {
                # Check for platform extension failures (common issue)
                if ($extType -eq "microsoft.iotoperations.platform" -and $extState -eq "Failed") {
                    Write-WarnLog "  Extension: $($ext.name) ($extType) - $extState (known issue - upgrade will fix)"
                    $failedExtensions += @{ Name = $ext.name; Type = $extType; State = $extState }
                } else {
                    Write-InfoLog "  Extension: $($ext.name) ($extType) - $extState"
                }
            }
        }
        
        # Check for failed extensions and provide remediation
        if ($failedExtensions.Count -gt 0) {
            Write-Host ""
            Write-Host "============================================================================" -ForegroundColor Yellow
            Write-Host "FAILED EXTENSIONS DETECTED" -ForegroundColor Yellow
            Write-Host "============================================================================" -ForegroundColor Yellow
            Write-Host ""
            Write-Host "The following extensions are in a failed state:" -ForegroundColor Yellow
            foreach ($ext in $failedExtensions) {
                Write-Host "  - $($ext.Name) ($($ext.Type)) - $($ext.State)" -ForegroundColor Red
            }
            Write-Host ""
            Write-Host "TO FIX THIS, run on your EDGE DEVICE:" -ForegroundColor Cyan
            Write-Host ""
            Write-Host "  az iot ops upgrade --name $instanceName -g $script:ResourceGroup -y" -ForegroundColor White
            Write-Host ""
            Write-Host "This will clean up failed extensions and update components to latest versions." -ForegroundColor Gray
            Write-Host ""
            Write-Host "============================================================================" -ForegroundColor Yellow
            Write-Host ""
        }
        
        # Check for missing required extensions
        $missingExtensions = @()
        foreach ($ext in $requiredExtensions.Keys) {
            if (-not $requiredExtensions[$ext]) {
                $missingExtensions += $ext
            }
        }
        
        if ($missingExtensions.Count -gt 0) {
            Write-Host ""
            Write-Host "============================================================================" -ForegroundColor Red
            Write-Host "MISSING REQUIRED EXTENSIONS" -ForegroundColor Red
            Write-Host "============================================================================" -ForegroundColor Red
            Write-Host ""
            Write-Host "The following extensions are required for IoT Operations but were not found:" -ForegroundColor Yellow
            foreach ($ext in $missingExtensions) {
                Write-Host "  - $ext" -ForegroundColor Red
            }
            Write-Host ""
            Write-Host "Without these extensions:" -ForegroundColor Yellow
            Write-Host "  - Assets created in the Azure Portal will NOT sync to Kubernetes" -ForegroundColor Gray
            Write-Host "  - Asset endpoints and dataflows will not function" -ForegroundColor Gray
            Write-Host ""
            Write-Host "TO FIX THIS, run on your EDGE DEVICE:" -ForegroundColor Cyan
            Write-Host ""
            Write-Host "  # Try upgrading the IoT Operations instance:" -ForegroundColor Gray
            Write-Host "  az iot ops upgrade --name $instanceName -g $script:ResourceGroup -y" -ForegroundColor White
            Write-Host ""
            Write-Host "If upgrade doesn't work, you may need to fully reinstall:" -ForegroundColor Cyan
            Write-Host ""
            Write-Host "  # 1. Delete the AIO instance:" -ForegroundColor Gray
            Write-Host "  az iot ops delete --name $instanceName -g $script:ResourceGroup --yes" -ForegroundColor White
            Write-Host ""
            Write-Host "  # 2. Wait for deletion to complete, then from Windows:" -ForegroundColor Gray
            Write-Host "  .\External-Configurator.ps1" -ForegroundColor White
            Write-Host ""
            Write-Host "============================================================================" -ForegroundColor Red
            Write-Host ""
        } else {
            Write-Success "All required extensions are installed"
        }
    } else {
        Write-WarnLog "Could not retrieve extension list"
        Write-InfoLog "Run: az k8s-extension list --cluster-name $script:ClusterName --resource-group $script:ResourceGroup --cluster-type connectedClusters -o table"
    }
    
    Write-Success "Verification completed"
}

# ============================================================================
# DEPLOYMENT SUMMARY
# ============================================================================

function Export-DeploymentSummary {
    Write-Log "Generating deployment summary..."
    
    $summary = @{
        deployment_timestamp = (Get-Date).ToString("o")
        subscription_id = $script:SubscriptionId
        subscription_name = $script:SubscriptionName
        resource_group = $script:ResourceGroup
        location = $script:Location
        cluster_name = $script:ClusterName
        iot_operations_instance = "$script:ClusterName-aio"
        storage_account = $script:StorageAccountName
        schema_registry = $script:SchemaRegistryName
        key_vault = $script:KeyVaultName
        namespace = $script:NamespaceName
        deployed_resources = $script:DeployedResources
        errors = $script:Errors
        dry_run = $DryRun.IsPresent
    }
    
    # Convert to YAML format
    $yamlContent = @()
    $yamlContent += "# Azure IoT Operations Deployment Summary"
    $yamlContent += "# Generated: $($summary.deployment_timestamp)"
    $yamlContent += ""
    $yamlContent += "deployment_timestamp: `"$($summary.deployment_timestamp)`""
    $yamlContent += "subscription_id: `"$($summary.subscription_id)`""
    $yamlContent += "subscription_name: `"$($summary.subscription_name)`""
    $yamlContent += "resource_group: `"$($summary.resource_group)`""
    $yamlContent += "location: `"$($summary.location)`""
    $yamlContent += "cluster_name: `"$($summary.cluster_name)`""
    $yamlContent += "iot_operations_instance: `"$($summary.iot_operations_instance)`""
    $yamlContent += "storage_account: `"$($summary.storage_account)`""
    $yamlContent += "schema_registry: `"$($summary.schema_registry)`""
    $yamlContent += "key_vault: `"$($summary.key_vault)`""
    $yamlContent += "namespace: `"$($summary.namespace)`""
    $yamlContent += "dry_run: $($summary.dry_run.ToString().ToLower())"
    $yamlContent += ""
    $yamlContent += "deployed_resources:"
    foreach ($resource in $script:DeployedResources) {
        $yamlContent += "  - `"$resource`""
    }
    $yamlContent += ""
    $yamlContent += "errors:"
    if ($script:Errors.Count -eq 0) {
        $yamlContent += "  []"
    } else {
        foreach ($err in $script:Errors) {
            $yamlContent += "  - `"$err`""
        }
    }
    
    $yamlContent -join "`n" | Set-Content -Path $script:DeploymentSummaryFile -Encoding UTF8
    
    Write-Success "Deployment summary saved to: $script:DeploymentSummaryFile"
}

function Show-CompletionSummary {
    Write-Host ""
    Write-Host "============================================================================" -ForegroundColor Cyan
    Write-Host "Azure IoT Operations Configuration Completed!" -ForegroundColor Cyan
    Write-Host "============================================================================" -ForegroundColor Cyan
    Write-Host ""
    
    if ($DryRun) {
        Write-Host "DRY-RUN MODE - No changes were made" -ForegroundColor Yellow
        Write-Host ""
    }
    
    Write-Host "Deployed Resources:" -ForegroundColor Green
    foreach ($resource in $script:DeployedResources) {
        Write-Host "  - $resource" -ForegroundColor Gray
    }
    Write-Host ""
    
    if ($script:Errors.Count -gt 0) {
        Write-Host "Errors encountered:" -ForegroundColor Red
        foreach ($error in $script:Errors) {
            Write-Host "  - $error" -ForegroundColor Red
        }
        Write-Host ""
    }
    
    Write-Host "Azure Resources:" -ForegroundColor Cyan
    Write-Host "  Subscription: $script:SubscriptionName" -ForegroundColor Gray
    Write-Host "  Resource Group: $script:ResourceGroup" -ForegroundColor Gray
    Write-Host "  Location: $script:Location" -ForegroundColor Gray
    Write-Host "  Cluster: $script:ClusterName" -ForegroundColor Gray
    Write-Host "  IoT Operations: $($script:ClusterName)-aio" -ForegroundColor Gray
    Write-Host "  Key Vault: $script:KeyVaultName" -ForegroundColor Gray
    Write-Host ""
    
    Write-Host "Azure Portal:" -ForegroundColor Cyan
    Write-Host "  https://portal.azure.com/#@/resource/subscriptions/$script:SubscriptionId/resourceGroups/$script:ResourceGroup" -ForegroundColor Gray
    Write-Host ""
    
    Write-Host "Next Steps:" -ForegroundColor Green
    Write-Host "  1. Review deployment summary: $script:DeploymentSummaryFile" -ForegroundColor Gray
    Write-Host "  2. Add secrets to Key Vault for Fabric RTI dataflows" -ForegroundColor Gray
    Write-Host "     (required because Fabric custom Kafka endpoints use SAS key auth, not Entra ID/Managed Identity)" -ForegroundColor DarkGray
    Write-Host "  3. Deploy edge modules using Deploy-EdgeModules.ps1" -ForegroundColor Gray
    Write-Host ""
    Write-Host "============================================================================" -ForegroundColor Cyan
}

# ============================================================================
# MAIN EXECUTION
# ============================================================================

function Main {
    try {
        Initialize-Logging
        
        Test-Prerequisites
        
        Import-ClusterInfo
        Import-AzureConfig
        
        # Validate cluster names match between config files
        Test-ConfigConsistency

        # Validate all required variables are present before doing anything
        Test-RequiredVariables
        
        Connect-ToAzure
        
        # Deploy infrastructure via ARM templates
        Deploy-Infrastructure
        
        # IoT Operations deployment (CLI-based)
        # Note: Arc enablement is done on the edge device via arc_enable.ps1
        Deploy-IoTOperations
        
        # Verification
        Test-Deployment
        
        # Summary
        Export-DeploymentSummary
        Show-CompletionSummary
        
    } catch {
        Write-ErrorLog "Unexpected error: $_"
        Write-Host ""
        Write-Host "Stack trace:" -ForegroundColor Red
        Write-Host $_.ScriptStackTrace -ForegroundColor Red
        throw
    } finally {
        Stop-Transcript
    }
}

# Run main function
Main
