apiVersion:  mqttbroker.iotoperations.azure.com/v1beta1
kind: Broker
metadata:
  name: broker
  namespace: default
spec:
  advanced:
    encryptInternalTraffic: Disabled
  cardinality:
    frontend:
      replicas: 1
      workers: 1
    backendChain:
      redundancyFactor: 1
      partitions: 1
      workers: 1
  generateResourceLimits:
    cpu: Disabled
  memoryProfile: "Medium"
---
apiVersion: mqttbroker.iotoperations.azure.com/v1beta1
kind: BrokerListener
metadata:
  name: listener
  namespace: default
spec:
  brokerRef: broker
  serviceType: LoadBalancer
  ports:
  - port: 1883