apiVersion:  mqttbroker.iotoperations.azure.com/v1beta1
kind: Broker
metadata:
  name: broker
  namespace: default
spec:
  advanced:
    encryptInternalTraffic: Disabled
  cardinality:
    frontend:
      replicas: 1
      workers: 1
    backendChain:
      redundancyFactor: 1
      partitions: 1
      workers: 1
  generateResourceLimits:
    cpu: Disabled
  memoryProfile: "Medium"
---
apiVersion: mqttbroker.iotoperations.azure.com/v1beta1
kind: BrokerListener
metadata:
  name: listener
  namespace: default
spec:
  brokerRef: broker
  serviceType: LoadBalancer
  ## This port will only be accessible within the cluster. If you want to access it from outside the cluster, you will need to expose it.
  ## Either use `kubectl port-forward aio-broker-frontend-0 1883` for low traffic testing or use a nodeport as shown in `deployment.complex.yaml`.
  ports:
  - port: 1883