/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace PtzClient.Ptz
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using PtzClient;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class ContinuousMoveRequestPayload : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// The Command request argument.
        /// </summary>
        [JsonPropertyName("ContinuousMove")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public ContinuousMove ContinuousMove { get; set; } = default!;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (ContinuousMove is null)
            {
                throw new ArgumentNullException("ContinuousMove field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (ContinuousMove is null)
            {
                throw new ArgumentNullException("ContinuousMove field cannot be null");
            }
        }
    }
}
