/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace PtzClient.Ptz
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using PtzClient;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class GetNodesCommandResponse : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// A list of the existing PTZ Nodes on the device.
        /// </summary>
        [JsonPropertyName("PTZNode")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public List<Ptznode> Ptznode { get; set; } = default!;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (Ptznode is null)
            {
                throw new ArgumentNullException("PTZNode field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (Ptznode is null)
            {
                throw new ArgumentNullException("PTZNode field cannot be null");
            }
        }
    }
}
