/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace PtzClient.Ptz
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using PtzClient;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class GetPresetsCommandResponse : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// A list of presets which are available for the requested MediaProfile.
        /// </summary>
        [JsonPropertyName("Preset")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public List<Ptzpreset> Preset { get; set; } = default!;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (Preset is null)
            {
                throw new ArgumentNullException("Preset field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (Preset is null)
            {
                throw new ArgumentNullException("Preset field cannot be null");
            }
        }
    }
}
