/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.9.0.0; DO NOT EDIT. */

#nullable enable

namespace PtzClient.Ptz
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using PtzClient;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.9.0.0")]
    public partial class GetStatusCommandResponse : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// The PTZStatus for the requested MediaProfile.
        /// </summary>
        [JsonPropertyName("PTZStatus")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public Ptzstatus Ptzstatus { get; set; } = default!;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (Ptzstatus is null)
            {
                throw new ArgumentNullException("PTZStatus field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (Ptzstatus is null)
            {
                throw new ArgumentNullException("PTZStatus field cannot be null");
            }
        }
    }
}
