/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.9.0.0; DO NOT EDIT. */

#nullable enable

namespace PtzClient.Ptz
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using PtzClient;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.9.0.0")]
    public partial class GetStatusRequestPayload : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// The Command request argument.
        /// </summary>
        [JsonPropertyName("GetStatusRequest")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public GetStatus GetStatusRequest { get; set; } = default!;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (GetStatusRequest is null)
            {
                throw new ArgumentNullException("GetStatusRequest field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (GetStatusRequest is null)
            {
                throw new ArgumentNullException("GetStatusRequest field cannot be null");
            }
        }
    }
}
