/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.9.0.0; DO NOT EDIT. */

#nullable enable

namespace PtzClient.Ptz
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using PtzClient;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.9.0.0")]
    public partial class GotoPreset : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// A requested preset token.
        /// </summary>
        [JsonPropertyName("PresetToken")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public string PresetToken { get; set; } = default!;

        /// <summary>
        /// A reference to the MediaProfile where the operation should take place.
        /// </summary>
        [JsonPropertyName("ProfileToken")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public string ProfileToken { get; set; } = default!;

        /// <summary>
        /// A requested speed.The speed parameter can only be specified when Speed Spaces are available for the PTZ Node.
        /// </summary>
        [JsonPropertyName("Speed")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public Ptzspeed? Speed { get; set; } = default;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (PresetToken is null)
            {
                throw new ArgumentNullException("PresetToken field cannot be null");
            }
            if (ProfileToken is null)
            {
                throw new ArgumentNullException("ProfileToken field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (PresetToken is null)
            {
                throw new ArgumentNullException("PresetToken field cannot be null");
            }
            if (ProfileToken is null)
            {
                throw new ArgumentNullException("ProfileToken field cannot be null");
            }
        }
    }
}
