/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace PtzClient.Ptz
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using PtzClient;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class OnvifError : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// The 'Message' Field.
        /// </summary>
        [JsonPropertyName("Message")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public string Message { get; set; } = default!;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (Message is null)
            {
                throw new ArgumentNullException("Message field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (Message is null)
            {
                throw new ArgumentNullException("Message field cannot be null");
            }
        }
    }
}
