/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.9.0.0; DO NOT EDIT. */

#nullable enable

namespace PtzClient.Ptz
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using PtzClient;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.9.0.0")]
    public partial class PtcontrolDirectionOptions
    {
        /// <summary>
        /// Supported options for EFlip feature.
        /// </summary>
        [JsonPropertyName("EFlip")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public EflipOptions? Eflip { get; set; } = default;

        /// <summary>
        /// The 'Extension' Field.
        /// </summary>
        [JsonPropertyName("Extension")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public PtcontrolDirectionOptionsExtension? Extension { get; set; } = default;

        /// <summary>
        /// Supported options for Reverse feature.
        /// </summary>
        [JsonPropertyName("Reverse")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public ReverseOptions? Reverse { get; set; } = default;

    }
}
