/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace PtzClient.Ptz
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using PtzClient;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.10.0.0")]
    public partial class Ptzvector
    {
        /// <summary>
        /// Pan and tilt position. The x component corresponds to pan and the y component to tilt.
        /// </summary>
        [JsonPropertyName("PanTilt")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public Vector2d? PanTilt { get; set; } = default;

        /// <summary>
        /// A zoom position.
        /// </summary>
        [JsonPropertyName("Zoom")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public Vector1d? Zoom { get; set; } = default;

    }
}
