/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.10.0.0; DO NOT EDIT. */

#nullable enable

namespace PtzClient.Ptz
{
    using System;
    using System.Collections.Generic;
    using Azure.Iot.Operations.Protocol;
    using Azure.Iot.Operations.Protocol.RPC;
    using Azure.Iot.Operations.Protocol.Models;
    using PtzClient;

    public static partial class Ptz
    {
        /// <summary>
        /// Specializes the <c>CommandInvoker</c> class for Command 'RemovePreset'.
        /// </summary>
        public class RemovePresetCommandInvoker : CommandInvoker<RemovePresetRequestPayload, RemovePresetResponseSchema>
        {
            /// <summary>
            /// Initializes a new instance of the <see cref="RemovePresetCommandInvoker"/> class.
            /// </summary>
            public RemovePresetCommandInvoker(ApplicationContext applicationContext, IMqttPubSubClient mqttClient)
                : base(applicationContext, mqttClient, "RemovePreset", new Utf8JsonSerializer())
            {
                this.ResponseTopicPrefix = "clients/{invokerClientId}"; // default value, can be overwritten by user code

                TopicTokenMap["modelId"] = "dtmi:onvif:ptz;1";
                if (mqttClient.ClientId != null)
                {
                    TopicTokenMap["invokerClientId"] = mqttClient.ClientId;
                }
                TopicTokenMap["commandName"] = "RemovePreset";
            }
        }
    }
}
