/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.9.0.0; DO NOT EDIT. */

#nullable enable

namespace PtzClient.Ptz
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using PtzClient;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.9.0.0")]
    public partial class SendAuxiliaryCommandCommandResponse : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// The response contains the auxiliary response.
        /// </summary>
        [JsonPropertyName("AuxiliaryResponse")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public string AuxiliaryResponse { get; set; } = default!;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (AuxiliaryResponse is null)
            {
                throw new ArgumentNullException("AuxiliaryResponse field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (AuxiliaryResponse is null)
            {
                throw new ArgumentNullException("AuxiliaryResponse field cannot be null");
            }
        }
    }
}
