# templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  {{- if eq .Values.endpointType "http" }}
  httpusername: {{ .Values.secrets.httpUsername | b64enc | quote }}
  httppassword: {{ .Values.secrets.httpPassword | b64enc | quote }}
  {{- else if eq .Values.endpointType "sql" }}
  sqlpassword: {{ .Values.secrets.sqlPassword | b64enc | quote }}
  {{- if and .Values.secrets.sqlUsername (ne .Values.secrets.sqlUsername "") }}
  sqlusername: {{ .Values.secrets.sqlUsername | b64enc | quote }}
  {{- end }}
  {{- end }}