/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.9.0.0; DO NOT EDIT. */

#nullable enable

namespace MediaClient.Media
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using MediaClient;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.9.0.0")]
    public partial class GetAudioSourceConfigurationOptionsResponsePayload : IJsonOnDeserialized, IJsonOnSerializing
    {
        /// <summary>
        /// The Command response argument.
        /// </summary>
        [JsonPropertyName("GetAudioSourceConfigurationOptionsCommandResponse")]
        [JsonIgnore(Condition = JsonIgnoreCondition.Never)]
        [JsonRequired]
        public GetAudioSourceConfigurationOptionsCommandResponse GetAudioSourceConfigurationOptionsCommandResponse { get; set; } = default!;

        void IJsonOnDeserialized.OnDeserialized()
        {
            if (GetAudioSourceConfigurationOptionsCommandResponse is null)
            {
                throw new ArgumentNullException("GetAudioSourceConfigurationOptionsCommandResponse field cannot be null");
            }
        }

        void IJsonOnSerializing.OnSerializing()
        {
            if (GetAudioSourceConfigurationOptionsCommandResponse is null)
            {
                throw new ArgumentNullException("GetAudioSourceConfigurationOptionsCommandResponse field cannot be null");
            }
        }
    }
}
