/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.9.0.0; DO NOT EDIT. */

#nullable enable

namespace MediaClient.Media
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using MediaClient;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.9.0.0")]
    public partial class ImageStabilization
    {
        /// <summary>
        /// Image Stabilization level.
        /// </summary>
        [JsonPropertyName("Level")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public int? Level { get; set; } = default;

        /// <summary>
        /// Image Stabilization mode.
        /// </summary>
        [JsonPropertyName("Mode")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public ImageStabilizationMode? Mode { get; set; } = default;

    }
}
