/* Code generated by Azure.Iot.Operations.ProtocolCompiler v0.9.0.0; DO NOT EDIT. */

#nullable enable

namespace MediaClient.Media
{
    using System;
    using System.Collections.Generic;
    using System.Text.Json.Serialization;
    using MediaClient;

    [System.CodeDom.Compiler.GeneratedCode("Azure.Iot.Operations.ProtocolCompiler", "0.9.0.0")]
    public partial class Ptzspeed
    {
        /// <summary>
        /// Pan and tilt speed. The x component corresponds to pan and the y component to tilt. If omitted in a request, the current (if any) PanTilt movement should not be affected.
        /// </summary>
        [JsonPropertyName("PanTilt")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public Vector2d? PanTilt { get; set; } = default;

        /// <summary>
        /// A zoom speed. If omitted in a request, the current (if any) Zoom movement should not be affected.
        /// </summary>
        [JsonPropertyName("Zoom")]
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingDefault)]
        public Vector1d? Zoom { get; set; } = default;

    }
}
