apiVersion: v1
kind: Secret
metadata:
  name: my-backend-api-secrets
type: Opaque
data:
  SERVICE_USERNAME: <base64 encoded username>
  SERVICE_PASSWORD: <base64 encoded password>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-backend-api-d
  labels:
    app: my-backend-api-d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-backend-api-d
  template:
    metadata:
      labels:
        app: my-backend-api-d
    spec:
      containers:
      - name: my-backend-api-d
        image: k3d-registry.localhost:5500/my-backend-api:test
        env:
        - name: SERVICE_USERNAME
          valueFrom:
            secretKeyRef:
              name: my-backend-api-secrets
              key: SERVICE_USERNAME
        - name: SERVICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-backend-api-secrets
              key: SERVICE_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: my-backend-api-s
  labels:
    app: my-backend-api-d 
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: my-backend-api-d
