---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: azure-iot-operations
  name: anomaly-conf
data:
  config.yml: |-
      logger:
        level: 0
      server:
        route: /anomaly
        port: 3333
      algorithm:
        temperature:
          lambda: 0.25
          lFactor: 3
          controlT: 90
          controlS: 20
          controlN: 10
        vibration:
          lambda: 0.25
          lFactor: 3
          controlT: 50
          controlS: 20
          controlN: 10
        humidity:
          lambda: 0.25
          lFactor: 3
          controlT: 80
          controlS: 20
          controlN: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: azure-iot-operations
  name: anomaly-detection
  labels:
    app: anomaly-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anomaly-detection
  template:
    metadata:
      labels:
        app: anomaly-detection
    spec:
      containers:
        - name: anomaly-detection
          image: ghcr.io/azure-samples/explore-iot-operations/anomaly-detection:latest
          imagePullPolicy: Always
          ports:
          - name: http
            containerPort: 3333
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          command:
            - "./bin/anomaly-detection"
            - "--stdin=false"
            - "--config=/etc/anomaly-detection/config.yml"
          volumeMounts:
            - mountPath: /etc/anomaly-detection/config.yml
              subPath: config.yml
              name: config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: anomaly-conf
---
apiVersion: v1
kind: Service
metadata:
  namespace: azure-iot-operations
  name: anomaly-svc
  labels:
    app: anomaly-detection
spec:
  ports:
  - port: 3333
    name: http
  type: ClusterIP
  selector:
    app: anomaly-detection