apiVersion: v1
kind: Service
metadata:
  name: my-backend-api-s
  labels:
    app: my-backend-api-d  # Changed to match Deployment labels
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: my-backend-api-d  # Changed to match Deployment labels
