apiVersion: v1
kind: Service
metadata:
   name: media-server-public
   namespace: media-server
spec:
   type: LoadBalancer
   selector:
      app: media-server
   ports:
      - name: "rtsp"
        protocol: TCP
        port: 8554
        targetPort: 8554
      - name: "rtp"
        protocol: UDP
        port: 8000
        targetPort: 8000
      - name: "rtcp"
        protocol: UDP
        port: 8001
        targetPort: 8001
      - name: "rtmp"
        protocol: TCP
        port: 1935
        targetPort: 1935
      - name: "hls"
        protocol: TCP
        port: 8888
        targetPort: 8888
      - name: "srt"
        protocol: UDP
        port: 8890
        targetPort: 8890
      # - name: "WebRTC-TCP"
      #   protocol: TCP
      #   port: 8889
      #   targetPort: 8889
      # - name: "WebRTC-UDP"
      #   protocol: UDP
      #   port: 8189
      #   targetPort: 8189
