name: krill_test

on:
  workflow_dispatch:
  push:
    paths:
      - samples/callout/**

jobs:
  call-mage-test:
    uses: ./.github/workflows/mage_tests.yml
    with:
      workdir: samples/callout/