name: device-simulator_build

on:
  workflow_dispatch:
  push:
    tags: 
      - 'v*.*.*-device-simulator'

jobs:
  call-docker-build:
    uses: ./.github/workflows/docker_build.yml
    with:
      registry: makocr.azurecr.io/device-simulator
      file: samples/device-simulator/Dockerfile
      context: .
    secrets:
      azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
      registryLoginServer: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      registryUsername: ${{ secrets.REGISTRY_USERNAME }}
      registryPassword: ${{ secrets.REGISTRY_PASSWORD }}
