name: device-simulator_test

on:
  workflow_dispatch:
  push:
    paths:
      - samples/device-simulator/**

jobs:
  call-mage-test:
    uses: ./.github/workflows/mage_tests.yml
    with:
      workdir: samples/device-simulator/