name: docker_build

on:
  workflow_dispatch:
  push:
    branches:
      - release/*

jobs:
  docker_build:
    name: 'Build docker containers'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    