name: docker_build

on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      file:
        required: true
        type: string
      context:
        required: true
        type: string
    secrets:
      azureCredentials:
        required: true
      registryLoginServer:
        required: true
      registryUsername:
        required: true
      registryPassword:
        required: true

jobs:
  docker_build:
    name: "Build docker containers and push to registry"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Login with Azure CLI
        uses: azure/login@a641126d1b8aa4d1fa005f4f92df94a3a4c4c906 # v3.1.0
        with:
          creds: ${{ secrets.azureCredentials }}

      - name: Azure Docker Login
        uses: azure/docker-login@15c4aadf093404726ab2ff205b2cdd33fa6d054c # v2
        with:
          login-server: ${{ secrets.registryLoginServer }}
          username: ${{ secrets.registryUsername }}
          password: ${{ secrets.registryPassword }}

      - name: Build and Push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          tags: |
            ${{ inputs.registry }}:latest
            ${{ inputs.registry }}:${{ github.sha }}
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          push: true

      - name: Build and Push if Pushed with Tag
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          tags: |
            ${{ inputs.registry }}:${{ github.ref_name }}
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          push: true
        if: ${{ github.event_name == 'push' }}