name: deploy_ghcr

on:
  workflow_call:
    inputs:
      file:
        required: true
        type: string
      context:
        required: true
        type: string
      name:
        required: true
        type: string

jobs:
  push-store-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Build Inventory Image"
        run: |
          owner=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker build ${{ inputs.context }} -f ${{ inputs.file }} --tag ghcr.io/$owner/explore-iot-operations/${{ inputs.name }}:latest
          docker push ghcr.io/$owner/explore-iot-operations/${{ inputs.name }}:latest
