name: http_grpc_callout_build

on:
  workflow_dispatch:
  push:
    tags: 
      - 'v*.*.*-http-grpc-callout'

jobs:
  call-docker-build:
    uses: ./.github/workflows/docker_build.yml
    with:
      registry: makocr.azurecr.io/http-grpc-callout
      file: samples/http-grpc-callout/Dockerfile
      context: .
    secrets:
      azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
      registryLoginServer: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      registryUsername: ${{ secrets.REGISTRY_USERNAME }}
      registryPassword: ${{ secrets.REGISTRY_PASSWORD }}
