name: http_grpc_callout_ghcr

on:
  workflow_dispatch:

jobs:
  call-docker-build:
    uses: ./.github/workflows/ghcr.yml
    with:
      name: http-grpc-callout
      file: samples/http-grpc-callout/Dockerfile
      context: .