name: krill_build

on:
  push:
    tags: 
      - 'v*.*.*'

jobs:
  call-docker-build:
    uses: ./.github/workflows/docker_build.yml
    with:
      registry: azbluefin.azurecr.io/krill
      file: Dockerfile
      context: ./samples/krill/
    secrets:
      azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
      registryLoginServer: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      registryUsername: ${{ secrets.REGISTRY_USERNAME }}
      registryPassword: ${{ secrets.REGISTRY_PASSWORD }}
