name: mage_tests

on:
  workflow_call:
    inputs:
      workdir:
        required: true
        type: string


jobs:
  mage_test:
    name: "Runs golang tests using mage command provided in libraries"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
      
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Setup Go 1.21
        uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4.3.0
        with:
          go-version: 1.21

      - name: Install Mage
        run: |
          go install github.com/magefile/mage@latest

      - name: Run CI Verification
        working-directory: ${{ inputs.workdir }}
        run: |
          mage ci