name: mage_tests

on:
  workflow_call:
    inputs:
      workdir:
        required: true
        type: string


jobs:
  mage_test:
    name: "Runs golang tests using mage command provided in libraries"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install Mage
        run: |
          go install github.com/magefile/mage@latest

      - name: Run CI Verification
        working-directory: ${{ inputs.workdir }}
        run: |
          mage ci