name: Build and Publish WASM Python Builder Image

on:
  push:
    branches: [ main, wasm ]
    paths:
      - 'samples/wasm/python/Dockerfile'
      - 'samples/wasm/python/schema/**'
      - 'samples/wasm/python/inject_pdb.py'
  pull_request:
    branches: [ main ]
    paths:
      - 'samples/wasm/python/Dockerfile'
      - 'samples/wasm/python/schema/**'
      - 'samples/wasm/python/inject_pdb.py'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/azure-samples/explore-iot-operations/python-wasm-builder
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: samples/wasm/python
        file: samples/wasm/python/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
