# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: iotoperations-pubsub
  namespace: azure-iot-operations
  annotations:
    dapr.io/component-container: >
      {
        "name": "iot-operations-dapr-components",
        "image": "ghcr.io/azure/iot-operations-dapr-components:latest",
        "volumeMounts": [
          { "name": "mqtt-client-token", "mountPath": "/var/run/secrets/tokens" },
          { "name": "aio-ca-trust-bundle", "mountPath": "/var/run/certs/aio-mq-ca-cert" }
        ]
      }
spec:
  type: pubsub.azure.iotoperations
  version: v1
  metadata:
  - name: hostname
    value: aio-mq-dmqtt-frontend
  - name: tcpPort
    value: 8883
  - name: useTls
    value: true
  - name: caFile
    value: /var/run/certs/aio-mq-ca-cert/ca.crt
  - name: satAuthFile
    value: /var/run/secrets/tokens/mqtt-client-token
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: iotoperations-statestore
  namespace: azure-iot-operations
spec:
  type: state.azure.iotoperations
  version: v1
  metadata:
  - name: hostname
    value: aio-mq-dmqtt-frontend
  - name: tcpPort
    value: 8883
  - name: useTls
    value: true
  - name: caFile
    value: /var/run/certs/aio-mq-ca-cert/ca.crt
  - name: satAuthFile
    value: /var/run/secrets/tokens/mqtt-client-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dapr-client
  namespace: azure-iot-operations
  annotations:
    aio-mq-broker-auth/group: dapr-workload
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mq-event-driven-dapr
  namespace: azure-iot-operations
spec:
  selector:
    matchLabels:
      app: mq-event-driven-dapr
  template:
    metadata:
      labels:
        app: mq-event-driven-dapr
      annotations:
        dapr.io/enabled: "true"
        dapr.io/inject-pluggable-components: "true"
        dapr.io/app-id: "mq-event-driven-dapr"
        dapr.io/app-port: "6001"
        dapr.io/app-protocol: "grpc"
    spec:
      serviceAccountName: dapr-client

      volumes:
      # SAT token used to authenticate between Dapr and the MQTT broker      
      - name: mqtt-client-token
        projected:
          sources:
          - serviceAccountToken:
              path: mqtt-client-token
              audience: aio-mq
              expirationSeconds: 600

      # Certificate chain for Dapr to validate the MQTT broker
      - name: aio-ca-trust-bundle
        configMap:
          name: aio-ca-trust-bundle-test-only

      containers:
      - name: mq-event-driven-dapr
        image: ghcr.io/azure-samples/explore-iot-operations/mq-event-driven-dapr:latest
